### ISSUE TITLE
Initial commit of code

### ISSUE THREAD

**Issue by dontlaugh** [Raku/doc-website#1]
We need to get the latest code from @finanalyst into the `main` branch of this repo.

**Comment by coke** [comment]
Can someone point me at his repo/branch? I can do the initial setup.

**Comment by dontlaugh** [comment]
Once this initial push is done, we need to protect the `main` branch and enforce a pull request workflow. Even if we allow people to self-merge (at first).

**Comment by finanalyst** [comment]
Initial commit completed. Steps to build in README. I have tested the steps on my PC.

**Comment by dontlaugh** [comment]
Thank you! <3
