### ISSUE TITLE
Where is update-css

### ISSUE THREAD

**Issue by dontlaugh** [Raku/doc-website#10]
The readme mentions

> The plugin SCSS (for example) can be changed, then updated into CSS using `./update-css <plugin-name>`

Does this executable live somewhere outside this repo? Or is it installed as a part of some other tool? See also #6

**Comment by finanalyst** [comment]
The explanation of update-css is in the section on `raku-collection-plugin-development`. This is a separate distribution. The intention is to separate the tools for developing plugins from the content to which plugins will be applied.

**Comment by finanalyst** [comment]
To make things easier, I have created a update-css and a test-all-plugins utility for this website.

But it means moving the test-plugin module from raku-collection-development-plugins to raku-collection, which is actually more logical. That is currently underway.

**Comment by finanalyst** [comment]
update-css and test-all-plugins added

**Comment by dontlaugh** [comment]
Thanks, @finanalyst!
