### ISSUE TITLE
git repo has case-insensitive duplicates

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#11]
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'OgdenWebb/plugins/typegraph/typegraphs/Int.svg'
  'OgdenWebb/plugins/typegraph/typegraphs/int.svg'
```

**Comment by coke** [comment]
Ideally we avoid this, but worst case have to insure tooling is on case sensitive filesystems.

**Comment by coke** [comment]
means I can't do any simple edits on windows.

**Comment by finanalyst** [comment]
OK. The svg is created within the Typegraph plugin (see OgdenWebb/plugins/typegraph)

However, the svg for the typegraphs are very rarely changed, so typegraph looks at the modification date of typegraph.txt and does not regenerate the svg's.

Closing this issue, and moving commentary to #17
