### ISSUE TITLE
Website should show reflog used in latest build

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#110]
There's no easy way to look at https://docs.raku.org/ and see which version of the git repository was used to build the version of the site we're looking at. We don't need to advertise it on every page, but something in the console, or hidden markup/comment, or an unlinked file displaying the git reflog of the last build would be great.

If something like this already exists, we should document it in the README.

**Comment by finanalyst** [comment]
@coke In terms of where to put the info, this is something we could add into the 'generated' pop-up.
However, I don't know how to actually obtain the information required:
- Is it a git command on the directory containing the local version of documents? So, it would be called after the `git pull` command has been completed
- Is it information that is the same for all the files in repo, or does every file have its own value?

I will add the info if you can tell me how to get it, even from a CLI

**Comment by coke** [comment]
We could do each file, but I'm suggesting we just do the latest commit for the local copy of repo, with:

```
% git remote -v
origin	git@github.com:Raku/doc.git (fetch)
origin	git@github.com:Raku/doc.git (push)
% git rev-parse --short HEAD
a8009b7a8
```

The repository can be viewed online at this point with:

https://github.com/Raku/doc/tree/a8009b7a8

**Comment by finanalyst** [comment]
@coke - I'll try to do this asap . Since in the build process, the local repo from which the build is made is synchronised, I assume that what we need to do is:
- run `git rev-parse --short HEAD` on the refreshed local repo to get the hash value '$h'
- create an anchor in the generated popup showing `https://github.com/doc/tree/$h`

**Comment by finanalyst** [comment]
closing as completed
