### ISSUE TITLE
Some pages are not linked from language.html

### ISSUE THREAD

**Issue by JJ** [Raku/doc-website#114]
## The problem

This [page](https://docs-stage.p6c.org/language.html) is supposed to be an introduction to everything. But it does not include, for instance, [`about.html`](https://docs.perl6.org/language/about)

## Suggestions

That page should probably link every other page, but if there's a good reason to avoid some, it's probably OK. Anyway, it would be interesting to know which pages are not linked and why.

**Comment by finanalyst** [comment]
@coke just reviewed this issue. It can be quickly resolved, but it is a content problem, not a website problem
1. the about page is already referenced twice on every page. The content of `about` needs some resolution, as per the discussion. So, I think this part of the issue can be considered resolved.
2. The non-appearance of `Independent Subroutines` on the language page in both the original website and in doc-website is quite simple. In the metadata of `Type/independent-subroutines.pod6`, the metadata category is 'basic' not 'fundamental'. Changing the metadata will allow this page to be included automatically.

I have created a PR in raku/docs #4203 to resolve 2 above.

I suggest this issue be closed

**Comment by finanalyst** [comment]
independent subroutines now in language.
closing this issue as completed
