### ISSUE TITLE
markdown bug in readme

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#12]
``
'_'
``

should be written as

``
'\_'
``

**Comment by finanalyst** [comment]
Could you provide more context. I generate MarkDown from Rakudoc using Raku-Pod-Render, so my template is incorrect. I'll need some more info to locate the error

**Comment by coke** [comment]
I'm not sure what additional context I can provide, but: line 36 in README.md has the literal text:
``
'_'
``

This markdown is the beginning of italics markup, e.g. _italics_ (look at the source of this comment). You can see this in the rendered README.md on github.

Instead, this should be escaped, as:

``
'\_'
``

which will then show a literal underscore with no italic effect. If you're using a tool, then this is a bug in the tool.

**Comment by finanalyst** [comment]
Thanks. I see that problem now, and another one later in the README.

**Comment by finanalyst** [comment]
Fixed in README
