### ISSUE TITLE
non-standard FormatCodes in Code snippets

### ISSUE THREAD

**Issue by cfa** [Raku/doc-website#124]
```pod6
L<need|/language/modules#need> MyModule;
```

in [docs/language/modules.pod6](https://github.com/Raku/doc/blob/main/doc/Language/modules.pod6#L117) is currently rendered as 

```
<a href="/language/modules.html#need">need</a> MyModule;
```

on https://new-raku.finanalyst.org/language/modules.html#use.

**Comment by coke** [comment]
new-raku is a one off put out by @finanalyst.

This looks fine on the soon-to-be-live

https://docs-dev.raku.org/language/modules.html#use

**Comment by cfa** [comment]
Same rendering issue on my local machine. As discussed on IRC, the problem (and difference from docs-dev) seems to be the highlighter.

**Comment by finanalyst** [comment]
@dontlaugh further to the above, the following is installed by raku-pod-render
```
raku-pod-render-install-highlighter
```
Run it once in the build environment. You will need to have versions of `npm` etc, but the installation binary should tell you which version.

**Comment by dontlaugh** [comment]
Does this depend on an exact version of node? Installation fails with this error

```
/home/builder/MoarVM/install/share/perl6/site/bin

Using npm version 8.5.5 and node 16.

Trying to create highlighter at /home/builder/.raku-pod-render/highlights

Use of uninitialized value element of type Any in string context.

Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.

  in block  at /home/builder/MoarVM/install/share/perl6/site/sources/307B635565AFF273CDA2EBA8DC255EDDB9F7C46A (InstallAtomHighlighter) line 40

Tried to open directory /home/builder/MoarVM/install/share/perl6/site/resources

  in sub MAIN at /home/builder/MoarVM/install/share/perl6/site/sources/307B635565AFF273CDA2EBA8DC255EDDB9F7C46A (InstallAtomHighlighter) line 40

  in block <unit> at /home/builder/MoarVM/install/share/perl6/site/resources/BB27173280B12F052060F9D682B4D0907F55A443 line 2

  in sub MAIN at /home/builder/MoarVM/install/share/perl6/site/bin/raku-pod-render-install-highlighter line 3

  in block <unit> at /home/builder/MoarVM/install/share/perl6/site/bin/raku-pod-render-install-highlighter line 1
```

**Comment by dontlaugh** [comment]
@finanalyst the open PR in your raku-pod-render repo appears to explain my error

**Comment by finanalyst** [comment]
@dontlaugh I've just merged the change. @cfa+ I've bumped the version of raku-pod-render to 4.4.1 and pushed it to fez. Please try `fez upgrade Raku::Pod::Render` , then run `raku-pod-render-install-highlighter` and let me know if this works.

**Comment by coke** [comment]
OPs original bug is now visible [on docs-dec](https://docs-dev.raku.org/language/modules.html#use)

**Comment by finanalyst** [comment]
Just looked at the original issue. I think this is an error in the original source that the new tooling has brought to light.

The issue concerns an example snippet of Raku code.
```
need MyModule;
```
which is coded as 
```
L<need|/language/modules#need> MyModule;
```
In a Raku script the first runs fine, the second generates a parse error.

Since examples in code blocks should run, the original source is patently wrong. There is no use case that I can think of that rationally needs this sort of coding.

I am creating a PR to remove the redundant link in the source

**Comment by cfa** [comment]
Interesting.

My reading of [S26](https://design.raku.org/S26.html#Formatting_within_code_blocks) is that `L<>` is permitted and should behave as it does outside of a code block:

> Although `=code` blocks automatically disregard all [formatting codes](https://design.raku.org/S26.html#Formatting_codes), occasionally you may still need to specify some formatting within a code block. For example, you may wish to emphasize a particular keyword in an example (using a `B<>` code). Or you may want to indicate that part of the example is metasyntactic (using the `R<>` code). Or you might need to insert a non-ASCII character (using the `E<>` code).
>
> You can specify a list of formatting codes that should still be recognized within a code block using the `:allow` option. The value of the `:allow` option must be a list of the (single-letter) names of one or more formatting codes. **Those codes will then remain active inside the code block.**

(emphasis mine)

So, I'm not sure `L<>` needs to be explicitly specified in this case. Rather, the issue seems to be whether `:allow`, as outlined in the synopsis, is the currently expected behaviour. 

Regarding

> The use case for `:allow` is to allow for emphasing, and I think was before syntax highlighting was introduced.

the use case seems  broader than that—it's to allow for *formatting*. Even with syntax highlighting enabled I may still want to link a substring in a code block (as in this `need` example).

+1 to documenting `:allow` on https://docs-dev.raku.org/language/pod.html.

**Comment by finanalyst** [comment]
@cfa I am in favour of not allowing Format codes inside a code block. IMO a code block should be Raku compilable code. A copy/paste of a snippet with Formating will lead to non compilation.

Also, looking more broadly, what happens when more Format codes, such as `D<>` are implemented with far more content?

**Comment by cfa** [comment]
>  IMO a code block should be Raku compilable code. A copy/paste of a snippet with Formating will lead to non compilation.

But code blocks aren't necessarily Raku code. For example,

```pod6
=for code :lang<ruby>
foo +     # In Ruby a trailing operator means parsing should continue
  bar +
  baz
```

should be highlighted as Ruby, not Raku. At the moment this is not the case (see [here](https://docs-dev.raku.org/language/rb-nutshell.html#Basic_syntax)); Perhaps this ought to be filed as a separate issue?

Meanwhile (to your broader point), we have sundry formatting issues like [this one](https://docs-dev.raku.org/type/Routine.html#trait_is_export) where `B<...>` is rendered as `<strong>...</strong>`.

**Comment by cfa** [comment]
Here are the snippets that likely to cause problems:

```
$ rak ':allow' 
Type/Routine.pod6
266:=begin code :allow<B>

Type/Variable.pod6
59:=begin code :allow<B L>
75:=begin code :allow<B L>

Type/Signature.pod6
863:=for code :allow<L>

Type/IO/Handle.pod6
63:=begin code :lang<text> :allow< B R >
87:=begin code :lang<text> :allow< B R >

Language/pragmas.pod6
81:=begin code :allow<C>

Language/operators.pod6
2801:=begin code :allow<B V>

Language/regexes.pod6
2384:=begin code :allow<B>
2395:=begin code :allow<B>
2418:=begin code :allow<B>
2438:=begin code :allow<B>

Language/quoting.pod6
21:=for code :allow<B> :skip-test<listing>
42:=for code :allow<B> :skip-test<listing>
48:=for code :allow<B> :skip-test<listing>
152:=for code :allow<B> :lang<text>
173:=begin code :allow<B L>
204:=begin code :allow<B>
217:=begin code :allow<B L> :preamble<my @neighbors = "Felix", "Danielle", "Lucinda">
251:=begin code :allow<B L>
269:=begin table :allow<L>
314:=begin code :allow<B> :preamble<my $color = 'blue'>
337:=for code :allow<B L>
361:=for code :allow<B L>

Language/unicode_entry.pod6
615:=begin code :allow<B> :lang<vim>
634:=begin code :allow<B> :lang<vim>
643:=begin code :allow<B> :lang<vim>

Language/modules.pod6
116:=begin code :allow<L> :skip-test<needs dummy module>
826:=begin code :allow<R> :lang<javascript>

Language/about.pod6
86:=begin code :allow<R> :lang<pod6>

Language/pod.pod6
752:=begin code :allow<B> :lang<pod6>
761:=begin code :allow<B> :lang<pod6>
773:=begin code :allow<B> :lang<pod6>
783:=begin code :allow<B> :lang<pod6>
791:=begin code :allow<B> :lang<pod6>

Language/functions.pod6
57:=for code :allow<B L>
135:=for code :allow<B>
```

**Comment by cfa** [comment]
P.S., [these](https://gist.github.com/cfa/26b2f935cbfe252739b1fda122bdcb5b) are all potentially problematic at the moment due to `:allow` or `:lang `specifications.

**Comment by finanalyst** [comment]
> In [rb-nutshell.pod6](https://github.com/Raku/doc/blob/main/doc/Language/rb-nutshell.pod6#L25-L28) should be highlighted as Ruby, not Raku. At the moment this is not the case (see [here](https://docs-dev.raku.org/language/rb-nutshell.html#Basic_syntax)); perhaps this ought to be filed as a separate issue?

We need two issues:
- whether or not to continue to support the `:allow` metatab on `=code` blocks. Lets leave this discussion in this thread.
- new syntax highlighter. There is another issue for a syntax highlighter. I am intending to do this, but for Raku only. However, I can try to make it more generic. The aim is for an illustrative syntax highlighter that only works for short snippets and may not be completely correct. Eg editor syntax highlighters always have to be correct.

**Comment by 2colours** [comment]
> whether or not to continue to support the :allow metatab on =code blocks. Lets leave this discussion in this thread.

Does that discussion not affect the specification of Raku overall? In which case it would make sense to migrate it to a place where everybody can see it as a language design question.

**Comment by finanalyst** [comment]
@2colours I was thinking about this too.
@coke can we move the last few posts here to Raku/doc?

**Comment by coke** [comment]
We can move the entire ticket to raku/doc, but not parts of it. If you want to do a partial move, please create a curated issue/discussion on raku/doc. If you want the whole thing, give this a thumbs up.

**Comment by cfa** [comment]
Might be more straightforward to create a new issue there, summarising and linking this discussion?

**Comment by cfa** [comment]
(The followup `doc` discussion is [here](https://github.com/Raku/doc/discussions/4216).)

**Comment by cfa** [comment]
Another instance of this issue was just reported: https://github.com/Raku/doc/issues/4250

**Comment by finanalyst** [comment]
The issue then is to revise the rendering of code-blocks so that :allow is correctly recognised.

There should be an update of `Raku/doc/Pod.rakudoc` to document the various code block tabs.

**Comment by finanalyst** [comment]
@cfa This is now resolved by a patch to the Block code template. 

The result can be viewed at [new raku pod](https://new-raku.finanalyst.org/language/pod). 

> **Note** The pod file at new-raku is a revision of the Pod file in Raku/doc. It has quite a few of the examples re-instated - they did not work in `Pod::To::HTML`
