### ISSUE TITLE
docs-dev isn't highlighting code

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#125]
https://docs-dev.raku.org/language/modules.html#use

for example looks like it's just putting blocks around code, not colorizing.

**Comment by coke** [comment]
This may be hiding an issue on #124

**Comment by finanalyst** [comment]
the default when there is no highlighter is to put `<pre>` blocks around code. It is not hiding colorising. there is no highligher present in the build environment. The fix is quite easy.

Closing as a duplicate of #124
