### ISSUE TITLE
add @altai-man to about page

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#129]
https://docs-dev.raku.org/about.html

should have a line about the intermediate website and his work.

**Comment by coke** [comment]
While we're in there: 'and refactored' is probably better written as 'and refactoring'

**Comment by finanalyst** [comment]
I originally put in far more about Altai-man in the about page. He change it back to 'feedback'. One of the first commits on this repo.

**Comment by coke** [comment]
the person you have linked for feedback isn't @Altai-man, it's @AlexDaniel.

**Comment by finanalyst** [comment]
@coke AHHHH my bad. I am a bit dyslexic and I get people's names wrong.
The text on the about is from [Altai-man's site](http://164.90.207.89:10010/about)
Would it be possible for you to send me an email with some suggested text for each person. A few people have contributed to this repo, and should be on the about. I think its different to a CREDiTs file that will be expanded in the future.

**Comment by Altai-man** [comment]
My absence from the credits of the original website (no, erm, "my version of the website"), which was afterwards copied to the latest one "as is", was intended, please bear with me.
I welcome mentioning other contributors that are not present on that page, of course.

**Comment by coke** [comment]
Should we remove AlexDaniel, who has contributed a ton to Raku, but maybe not the docs?

**Comment by AlexDaniel** [comment]
Of course. There are just three names on that list, I don't belong there.
