### ISSUE TITLE
pin dependency versions

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#14]
Please pin the dependency versions in META6.json to specific known-to-work versions.

**Comment by finanalyst** [comment]
Currently everything is at the most recent update on all modules.

**Comment by coke** [comment]
Yes, instead of "latest", we should specify the version we know works explicitly.

**Comment by finanalyst** [comment]
I agree, but its not at the top of my priority list at present.

**Comment by finanalyst** [comment]
partially complete

**Comment by finanalyst** [comment]
The only dependencies currently not pinned are `Perl6::Typegraph`. This is because I think there are Modules that have been updated / renamed to Raku. I intended to change to the updated versions, but was offline travelling when I implemented the typegraph plugin and have not had time to revise.

**Comment by finanalyst** [comment]
completed
