### ISSUE TITLE
generated from is not linking to the reflog 

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#145]
The link in the 'generated from' in the footer is 404'ing.
There should be a reflog value  that is concatenated onto the `github/Raku/doc/tree` path
Something is not quite working in the build environment,
The plugin is `Website/plugins/git-reflog`

**Comment by coke** [comment]
If the commit id isn't available, the URL can be shortened to https://github.com/Raku/doc/

so at least we can point the user back at the git repo.

**Comment by finanalyst** [comment]
@dontlaugh I do not know how to debug this problem. When I clone 'doc-website' and do a fresh build, the git-reflog is correctly obtained from the clone of `Raku/docs/doc` repo. So something is not quite working in your build environment, but I don't know how to replicate it.

The raku program responsible for getting the reflog does this
```
my $rep = $source-root.IO.parent;
my $proc = run <<git -C $rep rev-parse --short HEAD>>, :out;
my $reflog = $proc.out.slurp(:close).chomp;
```
`$source-root` is provided by `Collection` and may not be correctly accessed for some reason in the build environment. I wonder whether this may be a permissions problem. Does the user-id running `build-site` have permission to run `git -C <path to repo> rev-parse --short HEAD`?

**Comment by dontlaugh** [comment]
Where/how is $source-root set?

**Comment by finanalyst** [comment]
@dontlaugh It is a parameter passed by Collection to setup callables. 
The relevant file is `Website/plugins/git-reflog/add-ref-hash.raku`.

**Comment by finanalyst** [comment]
@dontlaugh 
> Make the plugin fail the build if it generates invalid output. Force the issue.
I can do a PR for `doc-website` that would force the issue. But will that affect the next production build?

**Comment by dontlaugh** [comment]
Nothing will make it to production until the issue is fixed. That's why it's good to fail the build if we're missing something. In general, do that for everything that isn't correct.

I'll work on making the build logs public to make this easier for us to debug. Just need to make sure no secret values are exposed.

**Comment by finanalyst** [comment]
@dontlaugh That sounds good. Just to be clear: 
- I can create a PR to `doc-website` and merge to main.
- Wait for an hour to see how the change pans out on `dev-doc.raku.org`
- Iterate until happy.
- Notify you when `doc-website` main is stable again?

If this is true, is there a way to trigger the rebuild of `dev-docs.raku.org` or is it triggered by a push to main.

**Comment by finanalyst** [comment]
The git-reflog plugin is causing errors elsewhere. 
This needs more investigation, so I am disabling the plugin.
There should be no adverse effect elsewhere.

**Comment by finanalyst** [comment]
issue now moot as functionality removed. Closing
