### ISSUE TITLE
Raku TM popup on footer does not have a dark theme

### ISSUE THREAD

**Issue by rawleyfowler** [Raku/doc-website#146]

**Comment by rawleyfowler** [comment]
Yeah I thought so too, I think that there must be a class missing on the new one.

**Comment by finanalyst** [comment]
That is entirely possible. If you could track it down, I'd appreciate the help.
By the way, I merged a PR of yours that worked nicely, and the issue disappeared before I could put a thanks in the comment.So thanking you here for previous help. 
When you change a plugin, would you add yourself to its config authors page too.

**Comment by coke** [comment]
We are removing the TM from that location.
