### ISSUE TITLE
URLS shouldn't require .html

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#147]
We need something at the container level to allow all non-.html links to work.

https://docs.raku.org/type/Str.html

vs. 

https://docs.raku.org/type/Str

**Comment by 2colours** [comment]
Related to https://github.com/Raku/doc-website/issues/84

**Comment by dontlaugh** [comment]
Right now we're using the "builtin", default nginx config from the upstream nginx container. As part of this I'll need to add that config to this repo, as well.

**Comment by dontlaugh** [comment]
Maybe something like this https://serverfault.com/questions/439284/nginx-rewrite-remove-html-from-url-with-arguments

**Comment by dontlaugh** [comment]
Possible fix; here's my test build

```
podman run -p 8080:80 quay.io/colemanx/raku-doc-website:rewrites
```

**Comment by finanalyst** [comment]
If this is working, then I will need to go through the templates and get rid of the `.html` additions.
before I do, @dontlaugh would you please check things like [/language/Grammars#grammars](https://docs.raku.org/language/grammars#grammars) works      [(Currently this works)](https://docs.raku.org/language/grammars.html#grammars)

**Comment by finanalyst** [comment]
@coke  Incoming routes now hit fully qualified pages in `dev-docs.raku.org`. So, this issue could be marked as complete
