### ISSUE TITLE
depend on cro

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#15]
We already document the issue with automatically installing Cro, we should still declare it as a dependency in meta6.json

**Comment by finanalyst** [comment]
When I was developing other modules including Cro, I was getting constant failures with CI. 

The problem with Cro testing is that all the tests are run. I think that most of the Cro tests in the public distribution should moved to xt/ and for a simple sanity test to be run for public installation. 

But that is a matter of distribution philosophy.

However, as a practical matter and to make sure that CI  works on my distributions, I do not have Cro as a dependency. However, you will find that in the `cro` plugin for the site (see OgdenWebb/plugins/cro), there is a test for the existence of Cro. If it does not exist, there is an error message and a suggestion to install it.

Further, Cro is only needed if the site is to be served locally. The cro plugin is only run at the completion milestone, and it is not involved in the generation of the html

**Comment by dontlaugh** [comment]
I'll try to get cro installing reliably in CI. If we can't, we'll cross that bridge.

It sounds like `"depends": { "runtime": { ... } }` is where we should declare this. I'm still not that good at META6.json, though.

**Comment by krakan** [comment]
I'm creating a docker image built on top of `croservices:cro-http` so there will be no need to install Cro.

**Comment by dontlaugh** [comment]
I'm in favor of splitting the difference: pre-install Cro in development containers to give developers an easy onramp to hacking on the website, but still declare Cro as a dependency.

**Comment by coke** [comment]
> I'm in favor of splitting the difference: pre-install Cro in development containers to give developers an easy onramp to hacking on the website, but still declare Cro as a dependency.

Sounds good

**Comment by finanalyst** [comment]
completed
