### ISSUE TITLE
The search functionality is broken when using the localcdn extension

### ISSUE THREAD

**Issue by demanuel** [Raku/doc-website#150]
There are some errors in the browser console:

https://i.imgur.com/lw0Wro8.png

"LocalCDN is a web browser extension for your Firefox that emulates CDNs (Content Delivery Networks). It intercepts the network traffic between a website and remote CDNs, finds supported resources locally, and injects them into the environment. All of this happens automatically, so no prior configuration is required."  (from the developers at https://codeberg.org/nobody/LocalCDN/wiki )

**Comment by coke** [comment]
Shouldn't this be a bug on the localcdn plugin, not on us?

**Comment by coke** [comment]
Looks like they have a jQuery specific FAQ that they rewrite the version of jQuery used sometimes.

**Comment by finanalyst** [comment]
Will this have an effect on #139 ?

**Comment by demanuel** [comment]
> Shouldn't this be a bug on the localcdn plugin, not on us?

I opened because it was working with the old version and now it isn't... So it was the new version that introduced the issue and also maybe someone would also have the same issue as me.

With a bit more investigation by using https://www.localcdn.org/test/check to test the site

it indicates that the issue is because "Crossorigin and/or integrity attributes". It also presents a solution within the extension configuration:

```
Solution:
• Firefox: Enable the HTML filter
• Other browsers do not support the HTML filter. Please disable LocalCDN for these websites.
```

**Comment by coke** [comment]
Given that the solution for non-FF is "disable localCDN" - I'm going to close this ticket, but it's good you opened it, because now others have a trail if they have a similar issue.
