### ISSUE TITLE
Add support for firefox theme switcher

### ISSUE THREAD

**Issue by voldenet** [Raku/doc-website#151]
Currently, themes always use the same stylesheet syntax and uses js to switch it:
```html
<link rel="stylesheet" href="/assets/css/search-bar.css"/>
<link rel="stylesheet" href="/assets/css/search-bar-light.css"/>
<link rel="stylesheet" href="/assets/css/search-bar-dark.css"/>
```
Firefox (and some other browsers supports [alternative style sheets](https://developer.mozilla.org/en-US/docs/Web/CSS/Alternative_style_sheets) via menu item, which could be supported by setting proper attributes on stylesheets (css files are grouped by title):
```html
<link rel="stylesheet" href="/assets/css/search-bar.css"/>
<link rel="stylesheet" href="/assets/css/search-bar-light.css" title="Light"/>
<link rel="alternate stylesheet" href="/assets/css/search-bar-dark.css" title="Dark"/>
```

**Comment by finanalyst** [comment]
@voldenet the new website has two themes - dark & light. They are supported by a JS script, which should make the change uniform across all Browsers, not just Firefox.

Are any more styles needed at present?
Would the change suggested here provide any more functionality than currently exists?

**Comment by coke** [comment]
Ideally, the change would support the same two themes, but integrating with the builtin theme functionality on firefox, and manually for others (that is, same as it does now).

**Comment by finanalyst** [comment]
closing this issue as complete. @voldenet ++
