### ISSUE TITLE
How to test changes to Tooling without affecting production?

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#152]
I have a change to the tooling to remove '.html' extensions inside links.
This is not - I think - necessary. Support for routes without '.html' has been resolved. So changing from explicit links to pages into a route form is just neat, but not necessary.

If I wanted to suggest this change, I would want to test a branch of the tooling on a `dev-docs` container.

How can this be done?

**Comment by 2colours** [comment]
This is strongly related to https://github.com/Raku/doc-website/issues/217, right?

**Comment by finanalyst** [comment]
@2colours yes this is related to #217. I was thinking how to implement a solution to this issue when I came up with the idea in #217. My bad that I did not simply attach the idea to this issue. 
But @dontlaugh assigned it to himself and I didn't know if he had done any work on it.

**Comment by dontlaugh** [comment]
> This is strongly related to #217, right?

You're correct. I'm going to close this as a duplicate, and respond over there.
