### ISSUE TITLE
css broken in prod, not dev?

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#163]
the latest code on main was deployed automatically to docs-dev, and it looked fine.

deployed it to prod, and now syntax highlighting is missing and everything is green on the main page. (chrome).

docs-dev still looks correct.

I redployed as @dontlaugh mentioned something earlier in the day about possibly getting a bad build. I also created a new build - same color issues.

**Comment by coke** [comment]
@cfa was able to hard reload and get prod working - i can do so in incognito, but not in my main chrome browser.

guessing we want to put in cache busters for our css - whenever we change or deploy, we should bump a dumb number (e.g. foo.css?id=1) to bust user caches.

**Comment by coke** [comment]
Prod site has the issue for me on mac m2 in chrome & safari - firefox is fine.

**Comment by coke** [comment]
when in "green mode", toggling the theme does nothing also

**Comment by coke** [comment]
<img width="1232" alt="Screen Shot 2023-02-27 at 8 22 46 PM" src="https://user-images.githubusercontent.com/50257/221728561-54270b6a-ae05-48f9-ba20-dbdd61b0cc2f.png">

**Comment by finanalyst** [comment]
This seems to be an infra structure problem. I'm still getting up to speed on containers. If there's something to change in the build chain upto the creation of assets, let me know.

**Comment by coke** [comment]
... and checking this morning, prod seems fine. anyone else see "green mode" since yesterday??

**Comment by cfa** [comment]
@coke I also saw the green theme / "green mode" yesterday (as we discussed).

AOK for me this morning too.

**Comment by coke** [comment]
Best guess is that perhaps some local storage was set before loading the page which didn't interact cleanly with the updated code, and eventually timed out.
