### ISSUE TITLE
Add section link to each section

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#165]
A common UI quality of life addition for sites is to have the heading link go back to the top of document, but on mouseover, have a section link appear that allows users to click to open the ID associated with that heading, so they can then save that particular link.

We should implement whatever the best practice is here.

**Comment by coke** [comment]
Looks like there's something here that didn't work on the example I tried:

https://docs-dev.raku.org/language/5to6-perlvar

click on Special Variables heading.

URL changes to https://docs-dev.raku.org/language/5to6-perlvar#Perl_to_Raku_guide_-_special_variables

But this URL doesn't correspond to loading that particular heading. which is just SPECIAL_VARIABLES

Additionally, this doesn't work at all for "General Variables" on this page, or "[$ARG, $_]", which both just go back to the top of the document.

Someone please help verify what the best practice is here, and then we can ensure that the site adheres to that. Currently we have a bugged version for just head1 items, it seems.

**Comment by finanalyst** [comment]
@coke  The ability to get the id of a heading was removed for a while and then not replaced. I will reinstate it. The old UX was for a hook symbol to appear on mouseover, and then a right click would move the id to the copy board.

**Comment by finanalyst** [comment]
The change turned out to be minor and should not break anything else.
@coke could you approve and merge the the PR, then we can see on docs-dev that nothing breaks,

**Comment by coke** [comment]
Done, team, please review and comment here.

**Comment by finanalyst** [comment]
the proposed change is live on [new-raku eg objects](https://new-raku.finanalyst.org/language/objects.html)

**Comment by cfa** [comment]
This is a definite improvement.

A question, though: why preserve the current link targets for the headings—is there any benefit to having all sections link to the top of the page given that the table of contents is in the sidebar?

**Comment by finanalyst** [comment]
@cfa No there is no need any more. It is a hold over from the very first web site. 
However, I think that before we change this, lets agree to what the sidebar behaviour should be. There's another issue about this.

**Comment by cfa** [comment]
Sure. Thanks for this change.

**Comment by finanalyst** [comment]
@coke can we close this issue?

**Comment by finanalyst** [comment]
completed
