### ISSUE TITLE
Search box expansion.

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#167]
Does the primary search box have any need to expand to fill most of a line?   I don't think I've ever entered more than twenty chars.  

To start, I found the expansion a cute gimmick, but quickly found it obnoxious for forcing my view to ping-pong across the window to find a place which could/should have been my current place.

I suggest a scrolling text box.  AN EDIT:   I mean one  to contain a reasonable numbers of chars and, when 'reasonable' is exceeded, allows panning over the text.

**Comment by finanalyst** [comment]
There are a number of things wrong with the search-bar, and I have never liked the functionality in the old site either. Long story short, we intend to re-write it completely. But there are obvious trade-offs for all ideas. So, we need to get some consensus on what is needed and how to change it.
There is a discussion topic on [search and extended-search](https://github.com/Raku/doc-website/discussions/127#discussion-4877967)

**Comment by finanalyst** [comment]
@0rir the new search function has a different UX, and this suggestion was taken into account.
Closing as completed. Please re-open if the concern has not been met.
