### ISSUE TITLE
Generated by should show time zone

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#168]
Was trying to check if an update of mine had hit yet, see:

```
This page is generated from

local_raku_docs/doc/Language/filename-extensions.pod6

on 2023-02-28 at 17:35:40
```

but then I realized I wasn't sure if this was my time zone, the servers, or UTC.

**Comment by finanalyst** [comment]
@coke do you have a preference for how this is expressed. Raku's datetime defaults to UTC, but I might be wrong

**Comment by coke** [comment]
Doesn't matter as long as it's correct.

**Comment by finanalyst** [comment]
I'll add UTC to the footer text

**Comment by coke** [comment]
.. Yes, but please verify that it's really UTC.

**Comment by coke** [comment]
Removing this entire item, closing ticket.
