### ISSUE TITLE
Apparently misleading "fatal" message during site build

### ISSUE THREAD

**Issue by cfa** [Raku/doc-website#169]
When building with `bin_files/build-site` on two different boxes, I've noticed the following line

```
fatal: cannot change to 'local_raku_docs': No such file or directory
```

in between the caching and rendering stages. I'm not sure which `Collection` step is attempting to change directory but `local_raku_docs` definitely exists and is pulled/updated each time I run the build script. Furthermore, the site builds just fine, so this "fatal" error appears to be a false positive from the user perspective.

Sample output from a recent run [here](https://gist.github.com/cfa/58e45e6e586b513f3dd2dc564e7a5c93). See line 13.

**Comment by finanalyst** [comment]
I do not think this is a "false positive". Some file has not been found, and a process has been prematurely ended. 
If a plugin callable fails, the Failure is caught but processing normally continues. The error may only be visible in the final site when something does not work correctly.

A lot more could be done to provide better debugging information when an error has occurred. 

There are a number of options to generate more information about where the problem occurs.

Try passing `--collection-info` into build-site. This shows each milestone in the Collection process, and the plugins that are called.

Try `bin_files/build-site --more-help` for more options.

**Comment by dontlaugh** [comment]
I would expect the following behavior from CLI programs:

* a "fatal" error stops execution immediately, and yields a non-zero exit code
* other kinds of errors (perhaps) allos execution to proceed, but still yield a non-zero exit code
* warnings just make noise in the logs, and do not affect the exit code

**Comment by dontlaugh** [comment]
"fatal" and "error" are kind of special words when it comes to logging output, in other words. Admittedly, this is merely a convention, but it's a common convention.

**Comment by finanalyst** [comment]
Agreed. This needs fixing. But I need a bit more information to track down why the Fatal is just being reported, and not throwing the process.

**Comment by cfa** [comment]
Excerpt from a run with `bin_files/build-site --collection-info`:

```
Plugin ｢raku-doc-setup｣ is listed for milestone ｢setup｣ and has keys ｢authors,version,name,auth,setup,license｣
Plugin ｢git-reflog｣ is listed for milestone ｢setup｣ and has keys ｢setup,custom-raku,render,license,template-raku,auth,version,authors,name,transfer,information｣
fatal: cannot change to 'local_raku_docs': No such file or directory
Starting ｢Setup｣ milestone
Rendering Collection on 2023-02-28 at 22:53:39
```

**Comment by cfa** [comment]
P.S. I referred to this as a false positive because 

1. the site builds in spite of the listed error, and
2. if it were truly fatal I would have expected the build to terminate prematurely

(which largely echoes what @dontlaugh mentioned above).

**Comment by finanalyst** [comment]
@cfa there is a problem with git-reflog that I am trying to work on. On my local machine, it works. On the build environment, it does not. 

The plugin runs a git command on the repo. Somehow the repo is not being found. 

I think that the information required (the reflog of the Raku/docs repo from which the sources are being pulled) is not urgent.

I think the git-reflog plugin needs to be disabled for a while.

In addition, I will look at Collection to make sure that Fatal warnings stop execution.

**Comment by cfa** [comment]
Thanks @finanalyst. Please let me know if/when you'd like me to test anything on my end.

**Comment by finanalyst** [comment]
This Fatal error is happening in git-reflog. The plugin is not working in the build envrionment as expected in any case.

So I am disabling the plugin.

**Comment by finanalyst** [comment]
plugin has been removed. Closing issue
