### ISSUE TITLE
Clarify the expected version of Sass

### ISSUE THREAD

**Issue by cfa** [Raku/doc-website#174]
The CSS update in https://github.com/Raku/doc-website/commit/e5df30ed ended up generating a lot of whitespace diffs, which seem to be the result of my using the Ruby rather than Node version of [Sass](https://sass-lang.com/). Mea culpa.

Can we document all of the expected non-Raku dependencies so that updates like this are done consistently?

**Comment by finanalyst** [comment]
There is a bash utility called `update-css` in the root directory which uses a `sass` binary that is installed with `apt`. The update-css utility is documented in README.
Did you use another way of generating the `css` from `scss`?

**Comment by finanalyst** [comment]
--version                  Print the version of Dart Sass.
richard@ged:~/tmp/DocWebsite$ sass --version
1.54.4
richard@ged:~/tmp/DocWebsite$

**Comment by cfa** [comment]
Thanks. So this is the Node versions of Sass, [installable](https://sass-lang.com/install) via `npm`.

**Comment by finanalyst** [comment]
@cfa Would it be possible for you to add a note in the README for future users. I hadnt realised there were multiple versions with significant output differences.

**Comment by cfa** [comment]
Yes, I'll add a note and refresh the CSS (via the script) with the correct version of `sass` in my path. Will send a PR in a few minutes.

**Comment by cfa** [comment]
PR: #180

**Comment by finanalyst** [comment]
closing this issue as completed
