### ISSUE TITLE
"Programs" page does not look correctly

### ISSUE THREAD

**Issue by Altai-man** [Raku/doc-website#175]
![image](https://user-images.githubusercontent.com/5764435/222133054-733c4e03-22c7-42af-81e7-db47982cbabe.png)

How it can look like:

![image](https://user-images.githubusercontent.com/5764435/222133132-db3a8a83-9fe6-487f-8af8-cc06fe415094.png)

**Comment by coke** [comment]
Duplicate of #106 - thanks for the screen shots!
