### ISSUE TITLE
camelia tm in header isn't "real"

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#182]
Replace the `tm` on camelia with 

™ - U+002122 - TRADE MARK SIGN [So]

**Comment by coke** [comment]
Let's try replacing

            <div class="navbar-logo-tm">tm</div>

with 

            <div class="navbar-logo-tm">™</div>

And see if it the style looks OK? (or can you try it locally and paste a screen grab?)

**Comment by finanalyst** [comment]
closed as idea explored and rejected
