### ISSUE TITLE
improve "in context"

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#186]
https://docs.raku.org/routine/STORE, e.g. shows content from other pages with:

See [Original text](https://docs.raku.org/type/Positional.html#method_STORE) in context

I recommend these be updated to something like:

_See primary documentation [in context](https://docs.raku.org/type/Positional.html#method_STORE) for **role Positional**_

**Comment by coke** [comment]
also header shows

> Synthesised documentation from type/Positional language/subscripts language/subscripts type/Associative

no need to list the elements here, they're in headings below. I suggest:

> Combined from primary sources listed below.

**Comment by finanalyst** [comment]
Ok, I'll deal with this now. The changes are simple enough.

**Comment by finanalyst** [comment]
closing as completed
