### ISSUE TITLE
Formatting codes are not working correctly in tables

### ISSUE THREAD

**Issue by cfa** [Raku/doc-website#195]
See for example https://docs.raku.org/language/regexes.html#Predefined_Regexes

This currently renders as

Regex \|Zero-width | Matches |  
-- | -- | --
\<same> | yes | Matches between two identical characters
\<wb> | yes | Word boundary
\<ws> | no | Whitespace, same as C« <!ww>\s* »
\<ww> | yes | Within word
\<ident> | no | Basic identifier (no support for C<'> or C<->). Same as C« <.alpha> \w* »

Note the third and fifth rows in particular.

**Comment by 2colours** [comment]
Oh yes, this is probably not particularly website relevant: https://irclogs.raku.org/raku/2022-09-29.html#13:26-0001

**Comment by cfa** [comment]
Good point.

I see that this is also documented as a restriction (and discrepancy with S26) [here](https://docs.raku.org/language/tables.html#Restrictions).

Closing as this is not a site issue.
