### ISSUE TITLE
extra space

### ISSUE THREAD

**Issue by interlab** [Raku/doc-website#196]
Url: https://docs.raku.org//type/IO::Socket::Async

Code highlighting seems to add an extra space? See screenshot:

![space](https://user-images.githubusercontent.com/2246621/71929592-9efc0180-31a2-11ea-820a-d92a6c22f687.png)

**Comment by finanalyst** [comment]
@coke this is related to syntax highlighting. There is a separate issue for this. A new syntax highligher could not be mapped to this issue in any case.
I suggest closing this.

**Comment by finanalyst** [comment]
Closing as relevant to highlighter and the issue has been opened there
