### ISSUE TITLE
Rewriting pointers to web fragments has stopped working

### ISSUE THREAD

**Issue by JJ** [Raku/doc-website#197]
## The problem

In the (temporary|new permanent) infrastructure, docs are served directly from Mojolicious, not using the .htaccess file that apparently rewrote hash fragments to reflect what's actually in there. So all links [like this one](https://docs.perl6.org/language/grammars#index-entry-ws-ws) (seen in Raku/doc#2211) have stopped working.

## Suggestions

There are 130 internal links that work this way:

```
git --no-pager grep "\#index-entry"  | wc
    140     680   15121
```

Fixing them is a lot of work, and will still make external links fail. So some way of rewriting should be reinstated, either in the infrastructure or at the documentation level.

**Comment by finanalyst** [comment]
@coke the link given in the opening post works. There are many other broken links, reported in error-report. [see errors](https://new-raku.finanalyst.org/error-report.html) 
This is covered in #25
This issue can be closed as completed

**Comment by finanalyst** [comment]
Original issue example resolved
