### ISSUE TITLE
divide Language page groups into separate pages

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc-website#202]
## The problem

Language page is too long and is growing.

## Suggestions

Split groups into separate pages with links from the Language page.

The change should be done after issue Raku/doc#2185 is closed.

**Comment by finanalyst** [comment]
@coke It is now much easier to split the language page. 

We create two new structure documents and add links to them in the header and the index page.

How about one page for Migration and Tutorials, and another for the other categories. Both pages would contain the section 'At the beginning'.

Call the first page 'Migration and Tutorials' and the second 'General and Reference'.

This might actually help with the constant complaint about the mixed nature of the documentation.

**Comment by finanalyst** [comment]
closed as completed
