### ISSUE TITLE
Typing a search term and hitting return always gives first result from menu of indexed items

### ISSUE THREAD

**Issue by briandfoy** [Raku/doc-website#203]
If I search for a term on docs.perl.org by typing in the search box and hitting return (so, not selecting something from the menu that pops up), I get the first thing in that menu. For instance, typing out "encoding" has a popup menu that only lists "study", so I get "study" if I hit return without selecting from the menu.

A "search this site with Google" option would be nice. Or even a different search box for that function.

**Comment by Altai-man** [comment]
This worked on the previous website, so some JS needs to be copied (right now, the "Enter to select" text is misleading, even though it does correct thing).

**Comment by 2colours** [comment]
On one occasion, we found that even your pace of typing and hitting Enter might change the output.

**Comment by finanalyst** [comment]
All of the requests in this issue have been incorporated into the new search refactoring. I think this issue should be closed.
@coke, please review.
