### ISSUE TITLE
404 on class diagram

### ISSUE THREAD

**Issue by librasteve** [Raku/doc-website#204]
## Problem or new feature

**Type relations for 404** on https://docs.raku.org/type/X::Control

**Comment by finanalyst** [comment]
@coke None of these links generate 404s on new site. 
I suggest this issue be closed.

**Comment by coke** [comment]
The class diagrams are missing.

**Comment by finanalyst** [comment]
fixed both problems above. Now if there are `Type/` sources without Typegraphs, it is because they are not generated. 
I suggest this issue is closed with the acceptance of the PR.

**Comment by coke** [comment]
We'll review once docs-dev gets this build, but we should also address the original issue that some diagrams were missing.

**Comment by finanalyst** [comment]
@coke original issue resolved as well. 
eg, X::Control
![image](https://user-images.githubusercontent.com/363676/227615477-ad783615-385d-4b18-bee5-69ecf9cd754f.png)

Also https://new-raku.finanalyst.org/type/Metamodel/C3MRO.html

**Comment by finanalyst** [comment]
closing as completed
