### ISSUE TITLE
"edit this page" points to renamed .pod6 files

### ISSUE THREAD

**Issue by 2colours** [Raku/doc-website#205]
Example: https://docs.raku.org/language/syntax.html - the button points at https://github.com/Raku/doc/edit/main/doc/Language/syntax.pod6

**Comment by coke** [comment]
This will be resolved with the next prod site push - please verify behavior in https://docs-dev.raku.org/ is working

**Comment by 2colours** [comment]
Indeed.

**Comment by coke** [comment]
Pushed.
