### ISSUE TITLE
Missing index entries

### ISSUE THREAD

**Issue by 2colours** [Raku/doc-website#206]
https://github.com/Raku/doc/edit/main/doc/Language/syntax.rakudoc

There is a part with the following rakupod tags:

```pod6
X<|Syntax,0b (radix form)>
X<|Syntax,0d (radix form)>
X<|Syntax,0o (radix form)>
X<|Syntax,0x (radix form)>
X<|Syntax,Number (literals)>
```

However, the radix forms don't appear in the search at all.

**Comment by finanalyst** [comment]
This is because glossary data is not included in the search data. The rationale is that there is a great deal of duplicated data (very many headings also have `X<>` markup), and the data structure is already very large.

**Comment by finanalyst** [comment]
@2colours I have figured a way to do this now. @coke please comment too.

FYI Many of the indexing commands in the Raku documentation use the form `X<display text|Syntax,0b>` The idea for indexes is that a single 'Syntax' entry will be followed by several sub-entries and page numbers (links). The two parts of the pair (here: `Syntax` and `0b`) have to be kept separate. 
The question is therefore how to display this in the search candidates list. Each item consists of
- a value, which is what is filtered according to the data in the search box
- an info value, which is displayed but not included in the search
- the url etc

In the main site (docs.raku.org), only the first item of the pair was put in the **value** section of the search element. So, if you enter *Syntax*, the **0b** will be shown somewhere down in the Indexed portion (if you have enabled Indexed candidates, default is disabled), but it will not be accessible for the search.
On [new-raku](https://new-raku.finanalyst.org), I have moved the second part of the index pair to the value part of the search candidates, so they will be accessible for the search input. 
Try searching for `0b` on the new-raku site.

If this meets the PR condition, please note here, and I will create a PR to move the change to doc-website.
