### ISSUE TITLE
Make "Search" field always visible again

### ISSUE THREAD

**Issue by vadz** [Raku/doc-website#209]
I'd like to suggest making the "Search" entry always visible, as it used to be on the old site, instead of requiring to click the hamburger in the top right corner to show it. My primary interaction with the site is via search and it's amazingly annoying to have to click one extra time to get to it now, especially when I still remember how much more convenient it used to be before. And there seems to be plenty of space for showing the search field near the hamburger button, which is not used for anything anyhow right now.

Thanks in advance for considering this!

**Comment by coke** [comment]
FYI, if you widen the browser, it should appear and stay visible. The ask here I think is to update the responsiveness to prioritize keeping the search present even at lower widths.

**Comment by lizmat** [comment]
Or maybe  not   :-)

**Comment by lizmat** [comment]
Related, some positioning issue:

![image](https://user-images.githubusercontent.com/2229339/223460911-3361afef-d828-4d75-ae09-21e14939a18f.png)

**Comment by vadz** [comment]
Oh, sorry, I should have thought about this. FWIW I am using one of my displays in portrait orientation, which is very convenient for reading documentation, and the window is maximized and, at 1200px wide, seems quite wide enough (inspecting the size of the inner div after moving the tab to a window on a landscape display I see that it's 1108px, so I'm really not sure why does it get hidden).

So this is less important than I thought, but still would be nice to improve.

BTW, I don't know if it's worth opening a separate issue for it, but it would also be great if there were a way to activate the search field from keyboard (if there already is one, I couldn't find it, after trying all those I could think of, such as <kbd>/</kbd>, <kbd>Ctrl+F</kbd>, <kbd>F3</kbd>, <kbd>Ctrl-Space</kbd>, etc).

**Comment by coke** [comment]
> BTW, I don't know if it's worth opening a separate issue for it, but it would also be great if there were a way to activate the search field from keyboard (if there already is one, I couldn't find it, after trying all those I could think of, such as /, Ctrl+F, F3, Ctrl-Space, etc).

Yes, please, and if you can link to any docs on "state of the art" here, I'd appreciate it. Last time this got raised on the old site, we had something ad hoc that no one liked; if there's a standard, everyone can get behind it.

**Comment by vrurg** [comment]
Here is what I see on my iPad:

![78A5184C-F6B1-4F39-8AB6-0F4F2603ADC1_1_201_a](https://user-images.githubusercontent.com/1586992/224514988-3083b751-95c6-4d84-8d9c-6f82baeb461d.jpeg)

While it's ok to have all the menu items hidden under the button, the search is, perhaps, one of the most required features of the docs. A keyboard shortcut may not work for iPad. But, as one can see, there is plenty of space to have the search input in it.

About the same applies to iPhone too: there is definitely enough room to plug the field into.

**Comment by finanalyst** [comment]
@vadz please review new UI [online review](https://new-raku.finanalyst.org/language/operators) for this issue.

@vrurg the change to a hamburger style is set at 'tablet' by the Bulma framework.

**Comment by coke** [comment]
looks like it's not visible at all on the new UI (unless you click the slider)

**Comment by finanalyst** [comment]
closing as original issue is now resolved by new UI. If new UI could be improved, better for these to be raised in new issue with specific new suggestions/descriptions
