### ISSUE TITLE
Document the semantic of need/require/use with module longnames

### ISSUE THREAD

**Issue by dakkar** [Raku/doc-website#211]
I couldn't find any explanation of the semantic of `use SomeModule:ver<1.0>:auth<fez:someone>:api<1>` and the like.

None of the "module packages", "modules" or "compunits" pages explain it (they mention long names, but only the declaration side, not the `use` side)

Questions that such documentation should answer include:
* "can I ask for any version >= 2.0.0 and < 3.0.0 ?"
* "can I use wildcards in the values? like `:ver<1.*>`, or `:auth<*:foo>`"
* "how exactly is each value matched against the compunits in the repositories?"

**Comment by 2colours** [comment]
This ticket might have a better place at https://github.com/Raku/doc/issues, if I understand correctly.

**Comment by dakkar** [comment]
you're probably right @2colours!

I opened it here because, while talking on IRC, it was suggested that I write a "doumentation bug report"; from the https://docs.raku.org/ site, the only link to report an issue links here.

Maybe I should open a bug about that ☺

/me copies this issue to the other repo

**Comment by 2colours** [comment]
> Maybe I should open a bug about that ☺

Yes, that actually sounds like a kind of bug. :)

**Comment by coke** [comment]
Repo admins can transfer tickets. Instead of adding people to close and reopen, please let the admins transfer them in the future.
