### ISSUE TITLE
Table of Contents is hard to use on iPad

### ISSUE THREAD

**Issue by vrurg** [Raku/doc-website#212]
Would it be possible to narrow down the content column when the Table of Content is shown? The current use scenario makes it somewhat headachy to use it:

1. Find the blue arrow button. Click it.
2. Click an item in the list
3. Find the blue arrow button again. Click it to see the actual content.
4. This is not what I was looking for. Proceed to 1, repeat.

Here is what I mean:

![D695E096-2FA8-46A4-90D9-434E94F5F650_1_201_a](https://user-images.githubusercontent.com/1586992/224515284-23fd1940-79a1-410a-bf66-c6f0fba24ea3.jpeg)

**Comment by finanalyst** [comment]
@2colours @vrurg There is a suggestion to rewrite the headers and TOC functionality. 
If a header (section title) is highlighted in the TOC, the section is made visible in the window immediately. 
I will work on this idea soon. It may address this issue.

**Comment by 2colours** [comment]
To be honest, I'm not sure how to read this, either, but I think this is essentially [my idea](https://github.com/Raku/doc-website/issues/93). Long story short: the ToC entry would be brought into vision (and highlighted) when the corresponding header is hovered, so completely the reverse logic to the ToC links that wouldn't change.

**Comment by finanalyst** [comment]
@2colours sorry, you did explain that before. I came across a documentation set recently that did the opposite - as I was suggesting. Now I cant find the example :( 
However, I found a site ( [Moodle dev](https://moodledev.io/general/documentation/structure) ) where the sidebar moves the rest of the text rather than covering it up.
Would this be better?
@vrurg do you have an example site that has a UX you find better?

**Comment by vrurg** [comment]
@finanalyst Nothing comes to mind at the moment, but Moodle you found does it rather good. And even though the pull-out button spanning all the way from the top to the bottom doesn't appeal visually it makes it easier to point mouse at. I'll try to remember and test it later with trackpad on iPad.

**Comment by vrurg** [comment]
Tried that site with trackpad and it does work well. I'd say, it's a good prototype.

**Comment by finanalyst** [comment]
@vrurg Please test the new UI for the documentation site. I have put up [an online version](https://new-raku.finanalyst.org/language/operators). I think this way of toggling the visibility of the ToC should address your comments in this issue

**Comment by vrurg** [comment]
Much better than it used to be! Though I tend to agree to the [comment](https://github.com/Raku/doc-website/discussions/127#discussioncomment-6708755) with regard to the visual appearances. Have a look at what it looks like on a ultra wide screen:

![Screenshot 2023-08-12 at 9 51 36 AM](https://github.com/Raku/doc-website/assets/1586992/7d3094fa-27b9-4add-8fcf-0a88f0a740df)

I'd say that having a content icon on the left (something like a ">" sign? a usability expert would do better here) and a looking glass on the right would be sufficient. With them aligned all the way left and right, respectively.

Speaking of iPad, it is definitely better now. I'd say that the content panel is too narrow:

<img width="1194" alt="image" src="https://github.com/Raku/doc-website/assets/1586992/63290817-544e-4a4e-86cb-63ce5a4dd002">

An effect only observable on iPad is duplication of the looking glass icon:

<img width="1194" alt="image" src="https://github.com/Raku/doc-website/assets/1586992/fd68d20a-8e6a-43f3-a160-dccc07fe56db">

I'd also say that the search results must not disappear when any other panel is clicked. And I'd rather expect the to occupy the entire search pannel:

![image](https://github.com/Raku/doc-website/assets/1586992/dd639b24-a7e5-40c4-8999-55b12ef0764c)

And here is what scrolling looks like on both iPad and desktop:

https://share.icloud.com/photos/023S_nmsIeshDQcaECOG1QXdg

Notice how attempt to scroll the search panel causes the entire page to jump up and down. My guess is that it happens in part due to the footer panel behavior which is normally is not visible, but when the entire page is scrolled to the end it pops up and then starts looking weird too:

![image](https://github.com/Raku/doc-website/assets/1586992/95875809-1fe4-482a-8300-f102622705b4)

See the gap between text bottom and the panel?

But overall it all looks like mere glitches of a work in progress.

**Comment by coke** [comment]
I am not a fan of the slider. Also having to review the search changes at the same time means getting this merged is less likely.

**Comment by finanalyst** [comment]
closing as issue seems to be resolved by new UI
