### ISSUE TITLE
search results scroll bar broken

### ISSUE THREAD

**Issue by u34p45** [Raku/doc-website#213]
Typing in the search field produces a preview list of results with a scroll bar when, like for 'name' there are enough results.
But click and hold on the thumb to scroll down closes the search preview instead of allowing scrolling.

Same problem in chromium and firefox current.

**Comment by finanalyst** [comment]
This is a known issue. There are multiple enhancements requested for the search bar.

**Comment by finanalyst** [comment]
The new search function has much better navigation features, and this issue in particular.
@coke please review for closing

**Comment by u34p45** [comment]
The thumb issue has gone away thank you! I can now at least scroll down the list on chromium and firefox current.

But the search is still not very functional: If I select "open in new tab" in the search settings, after I scroll down a long list of search results, I can open one in a new tab in Chromium current (fails in firefox current). But even in chromium, I loose my place in the search result list - where I wanted to scroll more and open more relevant hits.

**Comment by coke** [comment]
yes, there doesn't seem to be a way to use standard browser options to open a result in a new tab. I think there's a related issue about this elsewhere.

**Comment by finanalyst** [comment]
@u34p45 During the review process for the new search, one of the users explicitly wanted the search state to go to the top

**Comment by u34p45** [comment]
Is there an option in there that opens the search result as a web page (rather than a javascript thing)? From where I could use the normal browser facilities in both firefox and chromium?

I guess I at some point I can use google but that sounds unfortunate :-)

**Comment by finanalyst** [comment]
@u34p45 @coke @codesections So the suggestion here is for the following behaviour:
- if a candidate is selected and RightMouseButton is clicked, then the candidate is opened in a new tab, but the focus remains in the current window.
- if a candidate is selected and Enter is pressed, then either the window is changed to the selection, or a new tab is opened with that selection, and focus is taken to the new window.
- if search looses focus, by going to a new tab or by going off the search, then returning to the search, the first search candidate is the implicit state
-

**Comment by u34p45** [comment]
Right, as is, you can't use normal browser functions such as "open link in new tab on middle button click" because there is no link - just acive javascript regions.

**Comment by coke** [comment]
> * if a candidate is selected and RightMouseButton is clicked, then the candidate is opened in a new tab, but the focus remains in the current window.

I think you'll get this for free if they're html links.

**Comment by finanalyst** [comment]
There are some 6000 datapoints that the search filters through.
The autoComplete-js library filters these datapoints and places them in a list. It then acts on the selection. These are not `<a>` items but `<li>` items.

I'll look into adding a different type of action for RightMouseButton click on a selected item.

**Comment by coke** [comment]
they can be `<li><a></a></li>`, and that would be fine from an HTML standpoint.

**Comment by u34p45** [comment]
That would be my usual method: Try a search, open several possibly relevant hits as tabs. Learn enough through the open tabs to do a better search.

**Comment by u34p45** [comment]
Thank you!

**Comment by finanalyst** [comment]
@coke adding a `<a>` to the HTML is not quite so easy. The relevant code is at `Website/plugins/options-search/options-search.js` line 115

**Comment by finanalyst** [comment]
closing as duplicating #303
