### ISSUE TITLE
provide a "report an issue with the documentation" link

### ISSUE THREAD

**Issue by dakkar** [Raku/doc-website#214]
as far as I can see, the only "report an issue" link is the "Report an issue with this site" at the bottom of the menu, which goes to _this_ repository.

I couldn't find any link going to https://github.com/Raku/doc/issues to report issues with the docs themselves.

**Comment by coke** [comment]
My current thinking was to have a single link and then I or another dev can transfer the tickets between the repos with a single click. My concern with having two links is just the extra text needed to explain which is which. We can probably get a similar effect by updating the "submit a bug" template here to mention raku/doc, and we can put the explanatory text there.

**Comment by coke** [comment]
I've added a bug template on this repo that does this, closing this ticket.
