### ISSUE TITLE
Some coloring for syntax is weird

### ISSUE THREAD

**Issue by rawleyfowler** [Raku/doc-website#216]
If you goto: https://docs.raku.org/language/typesystem.html#subset

You'll notice that the subset declaration is all one color:

![image](https://user-images.githubusercontent.com/75388349/225751198-faa234a8-a89d-441f-a42a-8c14c40dda84.png)

I expect it to more accurately reflect how a subeset declaration looks like in a code editor, something like:
![image](https://user-images.githubusercontent.com/75388349/225756679-42adf0bd-3b1f-4144-94c0-e7484f1f38f0.png)

**Comment by finanalyst** [comment]
This is an artifact of the syntax highlighter. 
There are some other problems too. eg, the highlighter does not handle multiple HERETO 
There is an issue to replace the syntax highlighter.

**Comment by 2colours** [comment]
I think the syntax highlighter should rather be fixed than replaced; there is nobody to reliably provide a better highlighter anyway. https://github.com/Raku/atom-language-perl6

**Comment by finanalyst** [comment]
@2colours problem is that atom syntax highlighter has a very large stack of `node.js` dependencies and some of them have gone out of date.

**Comment by 2colours** [comment]
The way it's integrated into the site might be ineffective - but that has nothing to do with the output itself.

Regarding the output, we need to maintain it - emphasis on bo"we" and "need to", as in, it can't be let as it is, and there's nobody else who would magically do it.

I try to dedicate this weekend to sort some stuff out with it - firstly, ditch Coffeescript (and CSON) as a poorly aged dependency of the project. The repository needs to drift towards being a plain textmate highlighter format "content repository", much like Raku/doc is the content of the documentation and this repository is the actual exported form.

**Comment by 2colours** [comment]
For what it's worth, I did reorganize some things with the highlighter (without purposefully changing the content, from what I can tell) and the highlighting does seem different from the one given in the issue.

```raku
subset Positive of Int where * > -1
```

Although it is also different from the one seen here on Github, which does look better still...
![image](https://github.com/Raku/doc-website/assets/37218286/e7647503-7d96-4896-9dc0-3c97b8dea798)

By the way, isn't the snippet just stupid? Sure, it's just demonstration but what's the added value of having a wrong definition of "positive" there? I think it just makes us look silly. I will change that.

**Comment by finanalyst** [comment]
This issue is now redundant IMHO due to change of syntax highlighter. Closing. Address any similar issue in #419
