### ISSUE TITLE
Matches in Language should get priority

### ISSUE THREAD

**Issue by lizmat** [Raku/doc-website#222]
If you're interested in a general explanation of regexes, it gets shown *way* below in the list, with a lot of fuzzy matches first.

I think generally any match on a filename in "language" should be shown as the first option.

![image](https://user-images.githubusercontent.com/2229339/226641387-c97d0c67-ca83-49e7-b148-9ce0a32522f5.png)

**Comment by 2colours** [comment]
We have a zillion of search bar issues, both regarding the outlook and the content. So far, nobody had the time to take on that, apparently. I liked [the idea of Richard](https://github.com/Raku/doc-website/discussions/127) but so far it also hasn't drawn much attention.

**Comment by finanalyst** [comment]
FYI Not got a lot of time at present. Just solved missing 'syntax/' file
problem. IMHO It's a result of an awful hack and bad documentation
standards. But I have a solution that I'm soon posting.
Search is next priority.

**Comment by 0rir** [comment]
#127 was/is great, but it various points  should be addressed by more specific Issues like this #222.

The glossary should be considered for first place.

**Comment by finanalyst** [comment]
The ordering of the search candidates puts 'Language' files first in new search. I think this issue has been completed.
@coke, please review for closing
