### ISSUE TITLE
"About" link (and "Report an issue..") in the header is not clickable

### ISSUE THREAD

**Issue by dontlaugh** [Raku/doc-website#226]
The issue (reproduced by one other person in IRC) is that clicking "About" from the "More" drop down menu doesn't navigate me anywhere. See screenshot.

![image](https://user-images.githubusercontent.com/43583445/227266566-d9cabf61-4b42-465f-95f7-acab3bd1f3c1.png)

Bug reproduced in the following environments:

Firefox:
 - OS: Pop_OS 22.04 (Ubuntu variant)
 - Browser: Firefox
 - Version: 111.0 (64-bit)

Brave:
 - Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) unknown (64-bit)"
 - OS: Slackware Linux, 14.2

However, the link works when the browser's width is mid-sized. See this screenshot.

![image](https://user-images.githubusercontent.com/43583445/227267775-118bf461-576c-46a4-bf85-e992945119bf.png)

_Clicking "About" in mid-sized mode navigates successfully. This is the same browser and environment._

**Comment by finanalyst** [comment]
I'm using Ubuntu and Firefox, and the link works from both 
- `<header>->More->About`
- `<footer>->About`

I have tried this with different size formats (wide, tablet, mobile), after toggling theme. The 'About' link works in all of them. 

More information is needed to understand why this is happening in other environments. 

Using Firefox with Ubuntu , please navigate to a page, then F12, or Ctl+Shift+I, or Web developers tools (or equivalent debugging page in other environments). In the 'Inspector' tab, open the `<nav>` and `<div id="navMenu">` `<div class="navbar-start">` `<div class="navbar-dropdown">` (last one will be greyed).

I get the following:

![image](https://user-images.githubusercontent.com/363676/227511446-5796c145-1016-4897-9af3-eb3393f0d235.png)

It shows that the link `About` has href `/about.html`

Please indicate if something else is served.

**Comment by 2colours** [comment]
It works for me as well, Firefox 111, Ubuntu 20.04.

**Comment by finanalyst** [comment]
closing this because no further feedback after a month. Issue seems to have been resolved. If not, please reopen and provide more information.
