### ISSUE TITLE
Missing type graphs.

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#232]
It seems that all type graphs attached, usually appended, to doc pages  are unavailable.
A section just for type graphs could be an interim solution, and be a continuing asset for users.

**Comment by rawleyfowler** [comment]
I noticed these were missing a while back, but I think it's intended ?? Not exactly sure.

**Comment by finanalyst** [comment]
This is not intended. 

The typegraphs have not been generated for the build environment. If you look at [new-raku](https://new-raku.finanalyst.org), which uses the same tool kit, you will see the typegraphs. 

I will generate them and create a PR to handle this.

**Comment by finanalyst** [comment]
@0rir @rawleyfowler please look at docs-dev.raku.org to verify that TypeGraphs are now added.

**Comment by 0rir** [comment]
@finanalyst, looks good!

**Comment by finanalyst** [comment]
@coke When docs-dev is transferred to doc, then this issue can be closed.

**Comment by finanalyst** [comment]
Typegraphs now attached. Closing issue
