### ISSUE TITLE
Extraneous formatting

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#233]
In  Language/quoting.rakudoc, at line 167 is unmarked, indented code where where code tags are being  rendered literally.

A few lines later  this 
```
=begin , code
my $color = 'blue';
say "My favorite color is $color!"; # OUTPUT: «My favorite color is blue!␤»
=end code

```
is rendered with an extraneous  http link and strong  tags.  There are many similar examples on that page.  These two are the only instances I have checked against the doc source.

 #124 describes somthing similar.

**Comment by finanalyst** [comment]
This is the same issue as #124 . It is a result of undocumented Rakudoc. I am closing this issue, and marking #124 as urgent
