### ISSUE TITLE
Build is failing due to change in Rakudoc source

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#236]
The last scheduled build that passed was  Build #784, which was a scheduled build on March 29 at 3.06pm

The next scheduled build was March 209 at 5.03PM #785. It failed.

Both 784 and 785 are based on the same commit 846ff14 This indicates that the changes in the commit itself did not cause the failures.

I cannot see what changed between 784 and 785

From the errors in the log, there appears to be an error rendering a `=item ` block in some source file. The error is being triggered in the renderer (ProcessedPod).

It seems from this that no changes after March 29 have been included in the Documentation.

<details>
<summary>Example logs</summary>

```
All candidates are currently installed

<git clone https://github.com/Raku/doc.git local_raku_docs/> was successful

Cannot resolve caller push(Str:D: Str:D); none of these signatures matches:

    (Any:U \SELF: |values)

    (Array:D: Slip \value, *%_ --> Array:D)

    (Array:D: \value, *%_ --> Array:D)

    (Array:D: **@values is raw, *%_ --> Array:D)

  in method handle at /home/builder/MoarVM/install/share/perl6/site/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 829

  in method handle at /home/builder/MoarVM/install/share/perl6/site/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 590

  in code  at /home/builder/MoarVM/install/share/perl6/site/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 678

  in method handle at /home/builder/MoarVM/install/share/perl6/site/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 674

  in method handle at /home/builder/MoarVM/install/share/perl6/site/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 590

  in code  at /home/builder/MoarVM/install/share/perl6/site/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 288

  in method process-pod at /home/builder/MoarVM/install/share/perl6/site/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 288

  in block  at /home/builder/MoarVM/install/share/perl6/site/sources/BA09FB708AC69E7DC34202CCED2B4134C6876510 (Collection) line 477

  in block  at /home/builder/MoarVM/install/share/perl6/site/sources/BA09FB708AC69E7DC34202CCED2B4134C6876510 (Collection) line 438

  in sub collect at /home/builder/MoarVM/install/share/perl6/site/sources/BA09FB708AC69E7DC34202CCED2B4134C6876510 (Collection) line 367

  in sub collect at /home/builder/MoarVM/install/share/perl6/site/sources/BA09FB708AC69E7DC34202CCED2B4134C6876510 (Collection) line 21

  in sub collect at /home/builder/MoarVM/install/share/perl6/site/sources/BA09FB708AC69E7DC34202CCED2B4134C6876510 (Collection) line 237

  in sub collect at /home/builder/MoarVM/install/share/perl6/site/sources/BA09FB708AC69E7DC34202CCED2B4134C6876510 (Collection) line 21

  in sub MAIN at ./bin_files/build-site line 5

  in block <unit> at ./bin_files/build-site line 3
```

</details>

**Comment by finanalyst** [comment]
Build #899 (11.03 9 April) still failing and for the same reason as on March 29. The first failure on March 29 was for a commit that succeeded two hours earlier (and several builds before that). Why did the build fail? 
The error logs are from ProcessedPod, but I cant get this to repeat.

**Comment by dontlaugh** [comment]
It's not a disk space issue. I've run `df -h` on the build server. That's one possibility we can eliminate.

* [link to log line here](https://buildkite.com/raku/doc-website/builds/905#01876757-eb61-4a22-b26c-54de0f36c7b7/48-58)
* [link to commit that shows how to add debugging commands here](https://github.com/Raku/doc-website/commit/054e78aabe07071f9225d983eb3f63fa1f67e7af)

**Comment by dontlaugh** [comment]
I've reproduced this error locally:

```
./bin_files/build-site --without-completion --no-status
```

Yields this error

```
Cannot resolve caller push(Str:D: Str:D); none of these signatures matches:
    (Any:U \SELF: |values)
    (Array:D: Slip \value, *%_ --> Array:D)
    (Array:D: \value, *%_ --> Array:D)
    (Array:D: **@values is raw, *%_ --> Array:D)
  in method handle at /home/coleman/.raku/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 829
  in method handle at /home/coleman/.raku/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 590
  in code  at /home/coleman/.raku/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 678
  in method handle at /home/coleman/.raku/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 674
  in method handle at /home/coleman/.raku/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 590
  in code  at /home/coleman/.raku/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 288
  in method process-pod at /home/coleman/.raku/sources/46368579988989AA8F42BD35145A1CE5CC2BE463 (ProcessedPod) line 288
  in block  at /home/coleman/.raku/sources/381B1B46CBF859104541DFA7F8152490C131F1EE (Collection) line 479
  in block  at /home/coleman/.raku/sources/381B1B46CBF859104541DFA7F8152490C131F1EE (Collection) line 440
  in sub collect at /home/coleman/.raku/sources/381B1B46CBF859104541DFA7F8152490C131F1EE (Collection) line 367
  in sub collect at /home/coleman/.raku/sources/381B1B46CBF859104541DFA7F8152490C131F1EE (Collection) line 21
  in sub collect at /home/coleman/.raku/sources/381B1B46CBF859104541DFA7F8152490C131F1EE (Collection) line 237
  in sub collect at /home/coleman/.raku/sources/381B1B46CBF859104541DFA7F8152490C131F1EE (Collection) line 21
  in sub MAIN at ./bin_files/build-site line 5
  in block <unit> at ./bin_files/build-site line 3
```

**Comment by dontlaugh** [comment]
Have there been changes in the required dependencies? CLI/binary dependencies, libraries, etc.

**Comment by finanalyst** [comment]
@dontlaugh It is possible there have been changes. I am trying to figure out a way to see where the change could be.
I shall now try to add more flags in, in the way you showed above.

**Comment by finanalyst** [comment]
@dontlaugh 
1. how did you create the commit `demonstrate_hacking_on_CI_pipeline`? I can see the branch in the build-kite webpage, but I do not see a PR or branch on this repo.
1. when you replicated the error, what was the environment? It seems that my local box has some dependency that is different to the one being cloned.

**Comment by finanalyst** [comment]
I have looked through the code dependencies. But another possibility is that there is an error in the Rakudoc of a source file from the Raku/doc repo. If that's the case, then ProcessePod should have flagged the error and reported which source file.

**Comment by dontlaugh** [comment]
Every push is built on CI. Do this.

```
git fetch origin
git switch --no-track -c 236-build-fail origin/main
git push -u origin 236-build-fail
```
Then go look at the Buildkite UI.

> What is best practice here?

Do not ignore errors, ever. Failing is the right thing to do. 

The scripts that we call from _this_ repo can help by providing better error messages about what exactly the problem is, rather than just throwing a cryptic exception.

**Comment by finanalyst** [comment]
The Collection module has been enhanced so that if ProcessedPod fails because of a Rakudoc error, then Collection will fail, reporting which source file was being processed when the failure occurred.

A PR has been raised to bump the Collection version to achieve this.

**Comment by finanalyst** [comment]
A PR in Raku/doc has been created to correct the failing source. There was a subtle error in the Rakudoc source. 
I will start work on ProcessedPod to create valid HTML from a malformed list.

**Comment by dontlaugh** [comment]
Be sure to link the commits back to this issue, so others can see how you implement this fix

**Comment by finanalyst** [comment]
PR that fixed this problem is [change to modules.rakudoc](https://github.com/Raku/doc/pull/4285).
Issue is co

**Comment by finanalyst** [comment]
closing issue as complete
