### ISSUE TITLE
Add date of build to website

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#238]
# Problem
A change to a Raku/doc source caused a build failure on March 29, 2023, but not noticed until Apr 9, because changes to sources are not immediately obvious.

# Proposal
Add information to `More->Build date` in the header about when the public facing website was generated. 

Information about when pages are generated used to be included in the footer, but this information seemed an unreasonable use of public facing window space, since builds are now conducted every two hours. 

However, although the information is not usually needed, when it is needed, it should be available.

The information could also be placed in a specific page, eg the `about` page.

It is relatively trivial to do this for the header, which is generated by a template. 
If it is better to be put on a page (eg. About), the fix would need a bit more difficult, but possible.

Any ideas / comments ?

**Comment by 2colours** [comment]
I think `about` would be nice but if it requires a design-ish change then I wouldn't insist on it.

Honestly, it could even be a Javascript alert box hidden behind a link, but again, only if it's simple to include the JS somewhere.

The main idea is, I think, that it should be a fairly opt-in thing. It could require more than one click to access it, even, given its low importance to the average user. For example, if adding a separate page is the simple thing, it could even be a link on the `about` page...

**Comment by finanalyst** [comment]
Date of generation exists at render stage. Commit id of repo is more difficult to access. But About page is best.

**Comment by dontlaugh** [comment]
Another alternative is to simply append an html comment to a well-known file.

```html
<!-- Build date: xxx commit-sha: xxx -->
```

This would only be visible to people choosing to view page source, but is also easily checkable via a script with `curl` + `grep`.

**Comment by lizmat** [comment]
If you're thinking that way, why not add it as a tooltip somewhere?

**Comment by finanalyst** [comment]
Currently Rakudoc sources are added to a cache using `Pod::From::Cache`. This is because compiling Rakudoc (aka POD6) files is a lengthy process and only needs to be done when the Rakudoc source is modified. I am adding a method to `Pod::From::Cache` that gets the commit id from the git sources. So calling the instance of the `Pod::From::Cache` class, which is needed to recover the Rakupod, yields the last commit id.
The commit id can be used with the generate date on the About page without too much fuss. I think it will look OK.

I'll create a PR for this in the near future.

**Comment by finanalyst** [comment]
@2colours  @lizmat @dontlaugh The effect of PR 238 can be seen at [new-raku /About](https://new-raku.finanalyst.org/about) (at end of text on page).

**Comment by 0rir** [comment]
Great!   Off topic:  Lack of dating on web products damages them more as time flies feed on them.  Please date your publications.

**Comment by finanalyst** [comment]
completed
