### ISSUE TITLE
Docs-dev not updating

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#248]
`docs-dev.raku.org` has not updated since May 2. From [docs-dev about](https://docs-dev.raku.org/about)
```
The web site was generated as follows:

    Based on commit 3de9c0a0e.
    Generated on 2023-05-02 at 10:31:40 UTC.
```
Build-kite has been building successfully every two hours.

@dontlaugh @coke

**Comment by dontlaugh** [comment]
This is a disk space issue. Fixing it up now.

**Comment by dontlaugh** [comment]
re-open if this issue persists
