### ISSUE TITLE
/language/optut.html not found by search.

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#249]
This may be a symptom related to a more generalized issue like #197.  Or not.

The 'Creating Operators' page is not in search contents for either 'creating' or 'operator'.

This is on @finanalyst's 'new-' site.

**Comment by finanalyst** [comment]
@0rir Good catch.
1. Not like #197 at all.
2. The candidate data for the search bar are in the form [value info url] where value is the field that is filtered by the search function, info is information related to the file associated with value, etc
  - value items are searched from headings and file names
  - value items are not searched from file TITLEs. 

Looking at the source files (especially the Language/ ones), it makes far more sense to have the document title as the search candidate. This may be the same as #140 

Note that if you search for `optut` which is the file name, you get `Creating Operators` in the info section.

**Comment by finanalyst** [comment]
Search candidates have been changed on [new-raku](https://new-raku.finanalyst.org)
Now File title is Candidate value, and info shows the subtitle.

**Comment by finanalyst** [comment]
closing as resolved
