### ISSUE TITLE
404 on new and old from parse-base: "See also: syntax for number literals"

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#254]
[https://new-raku.finanalyst.org/syntax/Number%20literals.html](https://new-raku.finanalyst.org/syntax/Number%20literals.html) is not found.

**Comment by finanalyst** [comment]
@0rir This is odd. Without the [.html the page](https://new-raku.finanalyst.org/syntax/Number%20literals) is found. 
Where is the link that gave you this url? The url should have been generated without '.html'

**Comment by 0rir** [comment]
@finanalyst, at the end of the section https://new-raku.finanalyst.org/type/Str#routine_parse-base.  And ditto on https://docs.raku.org/type/Str#routine_parse-base.

**Comment by finanalyst** [comment]
@0rir I've found and fixed the problem on new-raku. Creating PR here.
