### ISSUE TITLE
Toggle theme is not persistent

### ISSUE THREAD

**Issue by 2colours** [Raku/doc-website#26]
Right now, if one clicks on the "toggle theme" caption, it does work - however, a site reload or navigating to another page will reset to the light theme.

The themes are backed up by cookies. Perhaps it would be possible to fix them with some setting for the server - however, I think it's worth considering to switch to [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) which is a simple and stable API and won't send any data to the server.

**Comment by finanalyst** [comment]
The theme javascript was imported from Altai-man's implementation with minimal adjustment.

I also do not like cookies, and would be happy to see a PR that uses localStorage. I think changing the TOC/sidebar toggle to localStorage, which currently also uses cookies, would be good.

The JS that uses/drive both theme and sidebar cookies are in `Website/plugins/ogdenwebb/js/core.js' .

**Comment by 2colours** [comment]
Thank you, I'm looking into it.

**Comment by 2colours** [comment]
I switched to localStorage and had to realize that the main problem is that the theming depends on the linked stylesheets. Currently, both stylesheets are generated in the site unconditionally. The toggle button mangles with the stylesheets directly, that's why it could work at all.

For now, I think I can just add it to the JS to remove the appropriate stylesheet on page load...

**Comment by finanalyst** [comment]
2colours PR seems to have fixed this
