### ISSUE TITLE
The highlighter is not being triggered for code-blocks

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#260]
@dontlaugh @lizmat @coke @2colours 
When the renderer gets a code-block, it sends the string to a highlighter. Currently, the highlighter is a node.js app.
I thought some of the problem was due to changes to get `<B>` markup working. But that is not sufficient. I have looked at the templates that generate new-raku and those for the doc-website, but they appear to be same for the relevant templates.
Take, eg., `docs-dev.raku.org/language/101-basics` if you look at the first div with the class raku-code, the div containing the actual contents (of scores.txt) has not got any syntax additions. Compare that to the same div in `docs.raku.org/language/101-basics` and `new-raku.finanalyst.org/language/101-basics`.
Conclusion, the node.js highlighter is not being activated.
This could be a build problem, or it could be changes in the highlighter.

**Comment by dontlaugh** [comment]
Can you write a test that will fail the build if dependencier aren't present?

The CI env was migrated recently, perhaps 10 days ago. This could have been introduced then.

**Comment by dontlaugh** [comment]
I'm adding this script to the base CI image build. By this I mean the LXD container that actually runs the Buildkite agent, accepts work, and runs our build scripts.

```
#!/bin/bash
#
echo "Clone raku-pod-render"
git clone https://github.com/finanalyst/raku-pod-render.git

echo "Build raku-pod-render and highlighting tools"
cd raku-pod-render
# put "raku" on the PATH
export PATH=$PATH:$HOME/MoarVM/install/bin:$HOME/MoarVM/install/share/perl6/site/bin

POD_RENDER_HIGHLIGHTER=1 zef install --deps-only .
```

**Comment by finanalyst** [comment]
build is now failing.

**Comment by finanalyst** [comment]
@dontlaugh This problem has been around for the doc-devs for at least a week. 
@lizmat just let me know she may have a Raku alternative for simple syntax highlighting quite quickly. 
We should know in a couple of days.
If Liz's RakuAST variation works, then we can eliminate the Node.js dependency altogether.

**Comment by dontlaugh** [comment]
Okay, in the meantime I am working on adding the current version to the build environment. I'll open issues on your repo if I have trouble.

**Comment by dontlaugh** [comment]
Here are my changes that add the node-based highlighter to the buildkite containers

https://github.com/Raku/infra/compare/8fed48711a7d6e7cdd965a11cd8d0c6f2e392e68..cf58712b09d7115205bc8383bce2e94b4639d1f6

Then:
* I bake an LXD container w/ Packer
* I launch some instances of these into the env that Perl Foundation owns
* I trigger some rebuilds and watch [the pipeline](https://buildkite.com/raku/doc-website)

If all goes well, docs-dev will have highlighting again soon

**Comment by dontlaugh** [comment]
This appears to be fixed on docs-dev, which tracks `main`.

I've taken steps in our current build environment to install the highlighter code.

Additional steps we can take to guard against this happening again:
* Write a test that runs post-build that uses some rough-and-ready heuristic to determine if raku-pod-render added highlighting to generated html; maybe analyze the  `span` contents of rendered code blocks
* Update raku-pod-render to - if asked via config - throw an error if it doesn't detect the required highlighting tools in its environment https://github.com/finanalyst/raku-pod-render/issues/18

**Comment by finanalyst** [comment]
I'm going to open another issue to cover the test, because it is more general.
Closing this now as completed.
@dontlaugh ++
