### ISSUE TITLE
language/unicode_entry

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#268]
On the above page, most example _boxes_ are incorrectly rendered,  these seem to be, I imagine, less used language-formats, e.g. shell, emacs, vim,  &c.

**Comment by finanalyst** [comment]
@0rir I just noticed these myself. I'll try and fix as soon as possible.

**Comment by finanalyst** [comment]
The html escaping is an easy patch. The unknown language is more of a problem. Highlights-js is expecting, eg., `XML`, but the Rakudoc source is `xml`.
@coke Should the error be fixed in the source (here xml -> XML), or should the build tools be more flexible?

**Comment by coke** [comment]
[language/unicode_entry](https://docs.raku.org/language/unicode_entry)

If there is a known correct language, the source should be fixed. If there's not a match, a sane default should be used.

**Comment by finanalyst** [comment]
@coke sane default: the contents of `:lang` is normalised to upper case. This seems to fix most situations. @coke PR 269 needs authorising

**Comment by finanalyst** [comment]
closing as completed
