### ISSUE TITLE
any operators with '>' or '<' like e.g.  '==>' generate '== &amp;gt;' in header of page

### ISSUE THREAD

**Issue by MARTIMM** [Raku/doc-website#273]
## Html escaping problem

The header at the top of a doc page shows e.g. **infix &amp;lt;==** for an explanation of `<==`. This should show **infix <==**.  This goes for all operators where a `<` or `>` is involved.

Example pages are [infix =>](https://docs.raku.org/routine/=%3E), [syntax <<](https://docs.raku.org/syntax/%3C%3C) and [infix <==](https://docs.raku.org/routine/%3C==).

**Comment by finanalyst** [comment]
@coke This is a duplicate of another issue, which has been solved, I think. @2colours is there an example of this in the current doc-site? If so, I will fix

**Comment by 2colours** [comment]
@finanalyst 2 out of the 3 provided links (https://docs.raku.org/routine/=%3E and https://docs.raku.org/routine/%3C== ) have this problem in the title

**Comment by finanalyst** [comment]
@2colours Yes a different problem to the one where `==>` was incorrect in the search candidates.

**Comment by finanalyst** [comment]
@2colours @labster @coke @MARTIMM  I fixed the issue, which was in the secondaries plugin. `<head><title>...` for each secondary page was generated from HTML escaped name, but should be an un-escaped string. Also took opportunity to enhance secondaries by adding a Table of Contents, and improve information for search engine. 

The patches are visible on [new-raku see routine/=%3E](https://new-raku.finanalyst.org/routine/=%3E)

Patch for doc-website soon

**Comment by finanalyst** [comment]
closing as completed
