### ISSUE TITLE
Pod documentation that use :allow< > does not highlight as Raku code but as Pod

### ISSUE THREAD

**Issue by samcv** [Raku/doc-website#274]
Pod documentation that is: `=begin code :allow<B L>` highlights as Pod not Perl 6 code. It is the :allow which causes this.

htmlify.p6 passes these as Pod to the highlighter, and so it gets highlighted as such (this is to allow us to make things bold/other styles).

Proposed solution from the docs side: we need to parse this Pod and strip it of Pod tags, and insert special Unicode control codes which nobody will have in normal text. These control codes can then be removed in the htmlify.p6 side once the highlighter highlights them.

From the highlighter https://github.com/perl6/atom-language-perl6 side, we will tag these differently than normal code, so we can add that effect in the CSS.

**Comment by finanalyst** [comment]
This issue is still open, but it is now being discussed in view of new syntax highlighter.
Closing this issue as duplicate
