### ISSUE TITLE
Type graph tree  is out of place.

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#275]
On https://docs.raku.org/routine/ACCEPTS, the first presented usage adds the type's typegraph.

**Comment by finanalyst** [comment]
@0rir Thanks. This is a bug in the secondary plugin. Too much text is being taken from the primary source for the secondary page.

**Comment by finanalyst** [comment]
@0rir the patch should have fixed this. Please check in docs-dev.raku.org that the behaviour has been fixed. Please close thread if issue has been resolved.

**Comment by 0rir** [comment]
@finanalyst, the issue might stand or be replaced.  The bug is no doubt different:  a chart now appears about 85% through the generated page.  The rendering is good , so I have cropped it.
Say a word and I'll close this issue and open another.  Thanks.
![Screenshot from 2023-08-18 12-42-24](https://github.com/Raku/doc-website/assets/14331463/dd91cd31-ee7d-4f66-b611-c5d68cff14b5)

**Comment by finanalyst** [comment]
@0rir I'm sorry not to have been explicit. The patch is first applied to the Main branch, which is reflected in the [docs-dev development site](https://docs-dev.raku.org/routine/ACCEPTS) 

The docs-dev site is then pushed to docs.raku.org

**Comment by 0rir** [comment]
@finanalyst, thanks for the fix.  You were explicit, I was misplacing myself.
