### ISSUE TITLE
routine/changed contains a dangling header

### ISSUE THREAD

**Issue by 2colours** [Raku/doc-website#279]
**Describe the bug**
The page https://docs.raku.org/routine/changed (easily accessible by search) contains a header that belongs to no content:

![image](https://github.com/Raku/doc-website/assets/37218286/00b70e0b-bf9c-495f-aece-f013ed53093d)

**Expected behavior**
Judging by an older version: https://web.archive.org/web/20220121195426/https://docs.raku.org/routine/changed that header simply shouldn't be there.

I doubt this is browser specific but anyway, Windows 10 with Maxthon 7.1.6.1000

**Comment by finanalyst** [comment]
@2colours thanks. this is probably a duplicate of #275 .

**Comment by finanalyst** [comment]
@2colours the patch should have fixed this. Please check in docs-dev.raku.org that the behaviour has been fixed. If all's correct, please close the issue

**Comment by 2colours** [comment]
Yep, seems good now, thank you.
