### ISSUE TITLE
Proposed change in navigation bar

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#294]
Remarks in several issues suggest a change to the way pages are distributed among the index pages. This would also require a change to the navigation bar at the top of each page. Reasons are:
- there is too much content in the `Language` page
- there is too little content in the `Programs` page
- Tutorials , migration guides are lumped together with fundamental topics and reference.

These changes would be trivial to implement with the new website tooling because the source files contain all the necessary metadata. 

I propose the following index pages, and a restyling of the navigation bar so that hovering over each header gives a 'Tip' or 'Title' that describes what is in each page.
- Introduction, contains the sections 'in the begining, tutorials, migration guides' that are in the current language page.
![image](https://github.com/Raku/doc-website/assets/363676/67a872e9-46de-4bf5-afbf-79cab08e020e)
- Reference, contains the language sections 'fundamental topics' and 'general reference'
![image](https://github.com/Raku/doc-website/assets/363676/39b9db1f-2e93-4564-8bab-a879d1990418)
- Types (page remains as before, but new title/popup)
![image](https://github.com/Raku/doc-website/assets/363676/53499dcf-15b9-47d5-a4e5-e38dc73a3104)
- Routines (as types)
![image](https://github.com/Raku/doc-website/assets/363676/f2db7a96-95af-44df-a96f-b2673a928548)
- Miscellaneous, Merges the topics in the current Programs, and Experimental from Language
![image](https://github.com/Raku/doc-website/assets/363676/9df13c66-15c4-4a38-b8cc-2eadd8a68b03)
- RakuTM (currently this is RakuTM Homepage), however, the phrase  takes a lot of room. The title makes it clearer what the button refers to. By the way, this and the Chat are links out of the website rather than being related to the documentation website.
![image](https://github.com/Raku/doc-website/assets/363676/47c37e95-b403-4050-9b5f-44df2f1234ba)
- Chat (Currently 'Chat with us') like RakuTM Homepage, lots of words for an external link.
![image](https://github.com/Raku/doc-website/assets/363676/6e44c07c-e24d-4cf4-a74e-9f200e000807)
- More & Search no change.

@coke , @lizmat , @cfa, @Altai-man @2colours @Raku/core @Raku/docteam  Thoughts?

**Comment by 2colours** [comment]
For me, the changes would be very welcome.

Some additional thoughts, trying to keep it very simple:

- In my head, most of the "reference" are the types themselves, and the "fundamentals" don't quite feel "reference-ish" enough. But acknowledging that it's clearly better than the current situation, and that there won't be a perfect consensual solution, I feel okay with it overall.
- What I do think is important though, is consistent namings. I had no clue, for example, what "starting" refers to in the tooltip. Apparently there is an "at the beginning" section. These sort of names should converge into a common name so that they don't end up being vague. I think it's much more important that there be _one common_ name than the particular name itself.

**Comment by finanalyst** [comment]
@2colours Having a common name would be best. Putting 'at the beginning' in the title seemed too much. Perhaps we change 'At the beginning' to 'Starting'?
There are also 'Start', 'Preface', 'Foreword', 'Beginners', or may be 'Synopsis'.

**Comment by 2colours** [comment]
I'm okay with any of them... or is the point that all of this already exists some way?

**Comment by coke** [comment]
I am ok with the changes mentioned at the top of the ticket - I suppose it's easier to have more top level headings than add sub-headings in the top nav?

As for "Starting", I think this should be "Getting Started"

**Comment by finanalyst** [comment]
close as completed
