### ISSUE TITLE
Notes on latest search updates

### ISSUE THREAD

**Issue by vrurg** [Raku/doc-website#299]
The email from perl6-users has a phrase saying "Please comment in the issue opened on [github.com/Raku/doc-website](http://github.com/Raku/doc-website)", but I found no specific issue. So, here a new one comes.

I only gave it a very quick glimpse. 

- One problem so far: keyboard navigation doesn't work properly as there is no reaction on Enter. Besides, at some point the topmost item in the search stuck with selection on it while it was possible to move the real selection downwards. Haven't managed to replicate the situation though.
- The "i" button would, perhaps, make more sense with a gear-like icon since it's about settings.
- Search with Google is better be the last item of the search results and become the only one when no results found.

**Comment by vrurg** [comment]
Oh, BTW, when there is "Displaying 20 of 44 results" at the top – how do I get to see the other 24? I mean, perhaps opening the composite is an option. But it could be practical to have access to them from the search pane itself.

But otherwise so far it looks better then the previous version.

**Comment by MARTIMM** [comment]
I would like the search field at the top right as it is at the current site. I like it that way because it is a short move from the menu icon (also in the top right) to the search field when clicked on that menu icon.

**Comment by finanalyst** [comment]
@vrurg 
>  but I found no specific issue. So, here a new one comes.
My bad. I should have said a comment on the PR. Thanks for opening an issue.

Thank you to everyone for commenting so far. I'm looking at the ideas and how to make them work.

**Comment by finanalyst** [comment]
@vrurg @2colours made a similar point in comment in PR regarding 20 out of 240
Problem is with the output of the autocomplete library. Pagination of other results maybe? But I dont know if this is part of the autocomplete function.

**Comment by 2colours** [comment]
Well, if it knows the amount of results, I would think they can be retrieved somehow... and if they really cannot, maybe it would actually be better to not put it straight into the user's face that there are more results that cannot be obtained in any other way than guessing.

**Comment by finanalyst** [comment]
@MARTIMM I was trying to work out what you meant, but now I think I understand. So, to be clear:
when you access the site on a tablet (or resize the window on a desktop to below some threshold), the navigation bar has hamburger. If the hamburger is opened on the current site, the search window is placed in the upper right, whereas with the options-search, the window is placed below the navigation `div`. I think this is what you mean.
The problem arises because 'autocomplete-js' generates a new search window with a different default. I'll fix it.

**Comment by vrurg** [comment]
BTW, speaking of screen width, here is what happens with  the 'Content' button and the actual content on, for example, [this page](https://new-raku.finanalyst.org/type/IO/Handle), though it would look the same on any other page:

![Screenshot 2023-09-21 at 4 17 07 PM](https://github.com/Raku/doc-website/assets/1586992/33fb8e86-154c-459d-ab9d-85e3283714c2)

**Comment by finanalyst** [comment]
@vrurg  What is the browser / output device. Here's what it looks like on my device (17" laptop, Ubuntu, Firefox) with Firefox set to whole screen:
![image](https://github.com/Raku/doc-website/assets/363676/c9f16350-0f06-4637-957e-460794d36d50)

**Comment by vrurg** [comment]
Oh, of course I forgot to mention "ultra wide monitor"! 5120x1440.

**Comment by finanalyst** [comment]
@vrurg sigh! I think Bulma CSS [handles wide, but not ultra-wide](https://bulma.io/documentation/layout/container/#desktop-and-widescreen-maximum-widths).  I'm not sure what should be the behaviour in these contexts.

**Comment by MARTIMM** [comment]
A remark I saw in a commit:  'the `Ctrl-F` will make search visible and place cursor in box'.
My browser (firefox) does that but it is used to search for text on the displayed page! Not to find something on other pages.

**Comment by finanalyst** [comment]
@MARTIMM The new functionality is working from my development site [new-raku](https://new-raku.finanalyst.org). The new functionality has not been established on `docs.raku.org`, so you will get the Firefox default there. `Ctrl-F` works on new-raku.

**Comment by finanalyst** [comment]
These comments have all been considered and included in the final refactoring.
@coke please review for closing.

**Comment by coke** [comment]
alt-f, which I expect to be option-f on the mac, doesn't work for me on chrome mac, m2. Everything else is ok.

**Comment by finanalyst** [comment]
@coke I have never used a Mac, so I dont know how to handle this situation.

**Comment by coke** [comment]
Opened this last remaining issue in #308
