### ISSUE TITLE
Cannot open search results in a new tab

### ISSUE THREAD

**Issue by codesections** [Raku/doc-website#303]
When using the search function (both the on the currently-live site and the new-raku site implementing #298), it's not currently possible to open a search result in a new tab, either by right-clicking and selecting "Open Link in New Tab" or by pressing `Ctr-<return>`.

This is particularly frustrating when multiple search results appear (potentially) relevant and I would like to open them all without re-typing the query.  Ideally, we'd support both methods of opening in a new tab.

I believe that the issue is caused by intercepting the click events via JS and not having an `<a>` element in the HTML, which should give us the browser default behavior.

**Comment by finanalyst** [comment]
Currently on [new-raku](https://new-raku.finanalyst.org) the default is for selecting a search candidate will go to the same tab (I originally had the default opening in a new tab, but @coke said the normal behaviour was to open in the same tab). 
Type 'say', for example. Then type `Alt-Q` and select. Using Firefox, it opens in a new tab.
Alt-Q is the keyboard shortcut for 'open in a new tab'. The new option is store locally, so everytime you use the website (so long as the local storage is not deleted), it will open in a new tab. The option can be found by clicking on the 'cogs' icon.

**Comment by codesections** [comment]
That is definitely helpful.  But (imo) it's worth respecting web norms by letting users right click or use `Ctr-<return>` if we can – since those options are provided by default for links, many users will expect them.

But the `Alt-Q`/config option makes this a lower-priority issue.

**Comment by finanalyst** [comment]
@codesections 
1. I was not aware Ctrl-<return> / Right click was a web norm. 
2. there is a general problem as discovered in the 'search PR' comments, namely, using web-norms can have an effect not expected by a user, and there is a taste element for which shortcuts to use.

All of the shortcuts for `Website/plugins/options-search` are contained in a single object in the JS script. I would appreciate some help in making that configurable in some way.

**Comment by 2colours** [comment]
It seems to me that right now, search results are actually opened on a new page on the new-raku site.

**Comment by coke** [comment]
There's a setting you can tweak. You might want to remove app data/cookies for the site to check the default setting.

**Comment by finanalyst** [comment]
@2colours the previous default was to open in a new tab, then that was changed to open in current window. You've been testing continuously (MANY THANKS), so you've probablty got the old default.

Simply toggle with Atl-Q to get what you want. To get the new defaults, you'll need to delete the local storage cache for the domain. In Firefox, use developers_tools->Storage_tab->Local_storage when the browser is opened on the domain you are interested in.

**Comment by 2colours** [comment]
Thank you, this makes sense and it indeed worked.

**Comment by finanalyst** [comment]
@codesections @coke @u34p45
@coke & @codesections were right - just including a `<a>` into the list item rendering accomplishes most of the task.
I have patched the new behaviour to [new raku eg reference](https://new-raku.finanalyst.org/reference). If this behaviour is OK, I'll sync the patch to doc-website.

Hovering the mouse over the link section of the list allows for the browser's default to work. Ctrl-Enter will open in a new tab when the item is selected by cursor navigation. 

The styling seems to be OK without changing anything, and the `<a>...</a>` part is indicated.

**Comment by u34p45** [comment]
@finanalyst That works for me thank you very much! Just tested on your staging site: I can now open several search results in new tabs with the middle button - the normal behavior here. And I can do that before or in between scrolling back and forth the search result list (no more loosing my place) - either using the scroll thumb or moving with the keyboard's up and down. This update has also fixed it on Firefox which had a different failure mode before.

There are 2 rough corners: On Firefox the results box sometimes opens narrow - but resets to something usable when tweaking the browser window size. On Chromium and Firefox, part of the highlighted result region opens the new tab while the rest does something unexpected (pastes previous search terms into the search field). Once noticed, these don't bother me. Glad to have a working search! Thank you!

**Comment by finanalyst** [comment]
closing as resolved
