### ISSUE TITLE
The tables in the documents are very packed

### ISSUE THREAD

**Issue by 2colours** [Raku/doc-website#307]
This is not a bug per se, just feedback on the aesthetics.

Take https://docs.raku.org/language/packages#Pseudo-packages for example.

![image](https://github.com/Raku/doc-website/assets/37218286/bbaa42cb-03fd-4c00-9fee-50c99498c76c)

There is a two-column table and no spacing in between. Perhaps it would be better to separate the columns more.

It's probably only a matter of change in base.scss on the technical side once there is an exact idea what value to set.

**Comment by finanalyst** [comment]
@2colours this is fixed now in the docs-dev site, which will migrate to docs site soon.
Closing the issue as fixed

**Comment by 2colours** [comment]
Yes, I think this is better. Thank you!
