### ISSUE TITLE
syntax/ is an arbitrary Perl to Raku snippet

### ISSUE THREAD

**Issue by 2colours** [Raku/doc-website#309]
As discovered in #288 , when the bare `syntax/` route is accessed, the following generated site is accessed:

![image](https://github.com/Raku/doc-website/assets/37218286/b94042f5-8f18-4d10-abde-7f06be490660)

`routine/` for example would route to a custom 404 page. I don't know of dangling links to this site but the point is that there shouldn't be any anyway, and it would be good to know why some content makes it to this route.

**Comment by finanalyst** [comment]
@2colours  latest patch fixes this problem. Try [test site](https://new-raku.finanalyst.org).
please close this issue if you agree,

**Comment by 2colours** [comment]
Yes, it's good now, thank you!
