### ISSUE TITLE
<-> turned into a bidirectional arrow in a sub name in the ToC

### ISSUE THREAD

**Issue by 2colours** [Raku/doc-website#315]
Confer the https://docs.raku.org/type/Range page. In the sidebar, `&infix:<->` shows up as a bidirectional array:
![image](https://github.com/Raku/doc-website/assets/37218286/8bfd3671-2ea2-454f-88f9-c013d404726b)

When it's really just the good old subtract operator:
![image](https://github.com/Raku/doc-website/assets/37218286/718e79b6-2a36-4a14-af31-8b7dc3b60bfc)

**Comment by 2colours** [comment]
The search does the same thing, by the way.

**Comment by finanalyst** [comment]
@2colours I don't have the same problem 
![image](https://github.com/Raku/doc-website/assets/363676/5c6e68df-39b0-4238-bdf8-d92c77dbe442)
I think this may be a local browser / font optimisation

BUT I do note that the next two infix items in the ToC are incorrectly given as `infix:` blank  :(
and that is a rendering error

**Comment by donaldh** [comment]
The browser font has a ligature for `<->`. Need to disable ligatures with `font-variant-ligatures: none;`

**Comment by finanalyst** [comment]
closing as completed
