### ISSUE TITLE
Typegraphs could do with a dark theme

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#33]
Most if not all Type pages have a Typegraph at the end of the page. This is generated svg. The Typegraph looks fine with the light theme, but does not look so good with the dark theme.

It seems that [svg elements can have a theme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#embedded_elements).

The Typegraphs are generated using Doc::Typegraph.

**Comment by rawleyfowler** [comment]
I can do this if you'd like?

**Comment by coke** [comment]
I very much appreciate the offer - @finanalyst, this OK with you?

**Comment by finanalyst** [comment]
yes please

**Comment by finanalyst** [comment]
Status report. Currently, the svg are generated in the typegraph plugin at `Website/plugins/typegraph` but only if the `typegraphs/` sub-directory is empty or the svg are older than the typegraph.txt file. 

The svg files are created using `Doc::Typegraph`. I have asked JJ to accept three options so that Nodes have hrefs with .html extension, no dot file generation, no file prefix. Currently, none of these options are possible. So, the href are altered with a s//, the dot files are removed, and so is the file prefix.

Since I have not studied how to create a theme for the svg, I do not know whether only CSS is needed, in which case, you can create two new SCSS files, eg typegraph-dark.scss, and typegraph-light.scss within the `typegraph` plugin directory . Use `./update-css typegraph` to generate the css, make sure that the `config.raku` file contains the css files in the add-css list (see the tablemanager plugin for an example).

**Comment by rawleyfowler** [comment]
I think it should be as easy as CSS, from what I have done in the past. I just hope that the typegraph svg's are not hardcoding too much.

**Comment by rawleyfowler** [comment]
#34

**Comment by finanalyst** [comment]
@rawleyfowler Could you look at the Routine page and issue #32 ? It is also a CSS dark problem. 
The relevant plugin is tablemanager.

**Comment by rawleyfowler** [comment]
@finanalyst I will take a look. Can you close this and ping me in a new issue so I can keep track?

**Comment by finanalyst** [comment]
completed
