### ISSUE TITLE
Rendering issue on safari

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#341]
Complaint:

> [15 hr. ago](https://www.reddit.com/r/rakulang/comments/1aexit9/comment/kkccet0/?utm_source=reddit&utm_medium=web2x&context=3)
> Hm. FWIW, that docs page doesn't render properly on Mobile Safari. Missing text cut off the right margin, not scrollable or zoomable to, just ... missing entirely.

Referring to:

https://docs.raku.org/type/Supply#sub_signal

**Comment by coke** [comment]
I see no issue on safari on the mac, even with a small viewport.

**Comment by lizmat** [comment]
Actually, I was able to reproduce this without doing the iPhone options.  It happens for certain kinds of width of the viewport.

**Comment by lizmat** [comment]
Going from wide to smaller:

Good:
![image](https://github.com/Raku/doc-website/assets/2229339/64f801a5-151b-4764-8397-e64754c04b66)

Bad:
![image](https://github.com/Raku/doc-website/assets/2229339/33179d44-8821-4be1-a2bc-a2fd00a3330c)

Good again:
![image](https://github.com/Raku/doc-website/assets/2229339/dac8cc0d-7192-4aa3-a667-7534a8911144)

**Comment by coke** [comment]
looks like the bad width is about 775 to 825 pixels

**Comment by finanalyst** [comment]
Is this issue only on one page,  or is it more generic?

Is the hamburger (three lines instead of a navigation top menu) being
shown? The hamburger indicates that the width is a problem with the
'tablet' set of CSS attributes (the bulma CSS environment has three
settings)

There are some issues with the tablet width on a pc too.

**Comment by coke** [comment]
Also happens on Chrome for certain widths (which seem different than the safari widths!)

It's generic, the original URL was just the one they were discussion on reddit.

The hamburger is shown at width X, where the rendering is fine and is on at any width below that. then at width Y (which is less than X), the formatting breaks. Then at width Z (which is less than Y) the text correctly flows again.

**Comment by finanalyst** [comment]
I have just had chance to test this. The problem is definitely with the 'Tablet' form. 
@rawleyfowler is this something you could help with? You have handled a CSS issue before.
A solution will be to adjust widths  in the SCSS under the 'page-styling' plugin

**Comment by finanalyst** [comment]
@coke @lizmat I found a fix. It changes the look and feel of main content pages a little bit, but the responsiveness is better, and it fixes this particular bug.
But it may change some other pages.
The fix is deployed at [new-raku](https://new-raku.finanalyst.org)

If you like the fix, I'll create a PR for doc-website.

**Comment by rawleyfowler** [comment]
@finanalyst Hey. I'm available if you need me, sorry I'm a father now so I have less and less time for OSS!

**Comment by coke** [comment]
it fixes the bug. one nit, it seems to increase the border.

**Comment by finanalyst** [comment]
Yes I just noticed that too. I'll have another look. I don't think that's
difficult to fix.
I'll ping you again when I fixed it.
Any other problems with other pages?

**Comment by coke** [comment]
That was the only thing I noticed

**Comment by finanalyst** [comment]
@coke reduced bottom margin, and increased the width of the main column. Looks better now. New CSS on new-raku. I'm creating a PR
