### ISSUE TITLE
Change the defaults on search?

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#342]
The search bar has options, which can be changed by clicking on the gear icon to the right of the bar. 
By default 'Indexed' data is disabled. This was done when the option was generating too many duplicates and not much extra searchable information.
A recent change allows for more Indexed data to be searched.
This issue is about whether to make the 'indexed' option enabled by default.
Any thoughts?

**Comment by dontlaugh** [comment]
Can you link to the commits here or in other repos that improved the indexed data implementation?

**Comment by finanalyst** [comment]
This was mentioned in #362 
 
@coke, we can make the Indexed items on by default quite easily. I'm posting a PR.

But localStorage will need to be changed by users to over-ride the previous default. I dont see an easy way to do this automatically as the whole point of having localstorage is for user choices to over-ride the default.

**Comment by finanalyst** [comment]
closing as resolved
