### ISSUE TITLE
qqx not found

### ISSUE THREAD

**Issue by JJ** [Raku/doc-website#347]
![Captura de pantalla de 2024-02-19 19-02-48](https://github.com/Raku/doc/assets/500/6680788a-ea51-4a74-9ddd-c551f2048b40)

## Problem or new feature

This directly from Google

**Comment by finanalyst** [comment]
@JJ  - I have created a PR in Raku/doc-website that fixes the problem. Thank you for highlighting it.
The PR has been merged and the result can be seen in docs-dev.raku.org
Deployment of docs-dev to docs.raku.org is always delayed to make sure bad errors are caught
