### ISSUE TITLE
Search dropdown half occluded on small display

### ISSUE THREAD

**Issue by patrickbkr** [Raku/doc-website#35]
![Screenshot_20230127-092239](https://user-images.githubusercontent.com/6307078/215041503-e4cd6663-a7b9-47ba-9010-40902b2957a6.png)

**Comment by rawleyfowler** [comment]
I can pick this up. I'll work on it tomorrow.

**Comment by finanalyst** [comment]
@rawleyfowler I was just about to ask you. Nice work on tablemanager. I added your name to the plugin authors.

This one will be more difficult to find. It will be in the ogdenwebb plugin. The SCSS is scattered around several files.

**Comment by rawleyfowler** [comment]
This can be closed.
