### ISSUE TITLE
URLs are not working on About page

### ISSUE THREAD

**Issue by Altai-man** [Raku/doc-website#36]
>[Aleks-Daniel Jakimenko-Aleksejev](https://new-raku.finanalyst.org/href=) - adapted web design for Raku documentation and implemented it with Documentable.

The URL should lead to github profile yet it's rendered... weirdly. The same happens with other URLs on that page.

**Comment by finanalyst** [comment]
This is odd. I'll deal with this first thing tomorrow morning

**Comment by finanalyst** [comment]
It seems to me this might be the same problem as in the Errors page. There is an issue with the rendering of the L<> code.

**Comment by finanalyst** [comment]
Link destination strings should not be quoted. see [pod links](https://new-raku.finanalyst.org/language/pod.html#Links)

But there was a problem with the rendering of Links as well.
