### ISSUE TITLE
Credits page does not exist

### ISSUE THREAD

**Issue by rawleyfowler** [Raku/doc-website#38]
On about page, there is a link to the credits page, but it just points to the about page. There is no credits page from what I can tell.

**Comment by finanalyst** [comment]
There should be a credits page, agreed. A list on the About page.

**Comment by finanalyst** [comment]
The link to the CREDITS in the main Raku/docs was not functional, but now is working. A CREDITS page for this distribution has been suggested by @coke.
So closing this issue
