### ISSUE TITLE
Documentation Bug: Heading link doesn't work

### ISSUE THREAD

**Issue by wayland** [Raku/doc-website#389]
## Problem or new feature

https://docs.raku.org/language/grammars#%22Always_succeed%22_assertion section link on section mark works, but the Table of Contents doesn't include the correct link.  

## Suggestions

Needs fixing, but not sure how.

**Comment by finanalyst** [comment]
The RakuDoc source is
```
=head3 X«"Always succeed" assertion|Regexes,<?>»

```
I'll check to see why `"` has not been quoted. I would have expected it to be.
