### ISSUE TITLE
Repl bar

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#4]
A REPL bar plugin (raku-repl) is included but not used because the CSS currently associated with it does not match the UX of the rest of the site.

A better rendering of the REPL bar is needed, and then the plugin can be enabled

**Comment by finanalyst** [comment]
The repl bar is now enabled. The styling is more in line with the overall UX. It lacks a dark theme.

The raku will need to be evaluated somewhere. The container with the Cro is quite simple.

**Comment by coke** [comment]
Please see discussion at #54

**Comment by finanalyst** [comment]
Repl-bar is disabled.
