### ISSUE TITLE
Error report incorrectly errors on https://docs.raku.org/type/Cool#typegraphrelations

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#401]
type/Cool has a link to its anchor: `#typegraphrelations` - if you go to https://docs.raku.org/type/Cool#typegraphrelations, that works, but the error-report claims this is an invalid item. (presumably because it's added in a separate process - need to whitelist this anchor for any of the type pages, probably.

**Comment by finanalyst** [comment]
@coke  Understood and agreed. Typegraph links should be added to the valid links list (whitelisted) in the same way as Secondaries / Composite page links are added to the valid links list.
FYI in the next iteration of the Renderer, there is a mechanism for a plugin, such as the one that adds Typegraphs, to add information to the Table of Contents and Index.

**Comment by coke** [comment]
This error is still showing up in the error report:

https://docs-dev.raku.org/error-report

**Comment by coke** [comment]
... because I never merged the PR. Closing

**Comment by coke** [comment]
Verified on https://docs-dev.raku.org/error-report#Glitches_found
