### ISSUE TITLE
error report external link check is disabled

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#402]
Let's enable it - it's only running the test at build time, we do want to fix any broken external links.

**Comment by finanalyst** [comment]
@coke this option alone can take 5-10 minutes. Each external link takes a significant time (several seconds) for the ping to the site and back again. There are some tens of links in all the files.
I'll create a PR on dev-docs. That should do a test run and we can see the result.

**Comment by coke** [comment]
This seems like a lot of processing time just to get a positive server
response; We can leave it disabled here and I can add it (back?) to the
link checker that's in the repo. Let's do that, and you can focus on other
things.

**Comment by finanalyst** [comment]
Enabling is easy.
In `Website/configs/03-plugin-options` change `link-error-test ...` `:no-remote` to `:!no-remote`

**Comment by finanalyst** [comment]
The following is the sub called for each link:
```

    sub test-remote($url --> Str ) {
        state $http = LibCurl::HTTP.new;
        my $resp;
        try {
            $resp = $http.HEAD($url).perform.response-code;
        }
        if $! {
            $resp = $http.error;
        }
        # return blank if any stringified response code
        return '' if ?(+$resp);
        # any numerical response code indicates http link is live
        # failures with non 404 ok as well.
        return '' if ($resp ~~ / \:\s(\d\d\d) / and +$0 != 404);
        $resp
    }
```

**Comment by coke** [comment]
Closing - we can run this particular test in the docs repo now, which makes it easier to add to CI.
