### ISSUE TITLE
Searchbar for type-reference is bad on small screens

### ISSUE THREAD

**Issue by rawleyfowler** [Raku/doc-website#41]
The searchbar on the type-reference search page is not styled correctly. It stretches vertically.

**Comment by finanalyst** [comment]
do you have a screenshot?

**Comment by rawleyfowler** [comment]
@finanalyst 
![2023-01-28-101919_1920x1080_scrot](https://user-images.githubusercontent.com/75388349/215277337-cc4bd0ad-7a23-46f5-9f42-2d94398ab548.png)
That white bar on the left is the search bar

**Comment by finanalyst** [comment]
I cant get this behaviour. Is it still happening? If so, can you give me a list of steps to get it. Can you verify which browser you are using (shouldn't matter, but ...)

**Comment by rawleyfowler** [comment]
Hmm I can't seem to reproduce this, not sure.

**Comment by finanalyst** [comment]
The website has been actively developed during the last week, once consensus was reached about using Collection in place of Documentable. The initial set of commits is now in, so changes should be slower and more incremental.
Closing this issue for now.
