### ISSUE TITLE
Anchors being generated in the wrong place

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#410]
https://docs-dev.raku.org/type/Method#index-entry-*%___(extra_named_arguments)

The source for this has this anchor here:

```
X<|Syntax,*%_ (extra named arguments)>
Methods automatically capture extra named arguments into the special variable C<%_>,
where other types of L<C<Routine>|/type/Routine> will throw at runtime. So
```

But when you click on that link, it jumps to the code block immediately **after** the paragraph shown above.

Looking at the HTML source, it seems to be correct. I'm guessing this is a problem with the CSS, and that the correct text is hidden under the header.

**Comment by finanalyst** [comment]
@coke Yes, there is a CSS issue when the anchor is in the middle of a page and there is a sticky header. 
There is a fix, which I found for the previous web site design, but did not apply to this one. 
Lets keep this issue open until after the deployment of the Bulma v1 CSS framework - if it still exists there.
