### ISSUE TITLE
build-site script: Turn off progress bars?

### ISSUE THREAD

**Issue by dontlaugh** [Raku/doc-website#50]
Anything that looks fancy in the terminal usually looks bad in the logs. Is there a way to suppress the progress bar during the "caching" stages of ./bin_files/build-site?

```
local_raku_docs/doc: Caching files
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    <--- that stuff
Completed in 6m:15s
```

**Comment by finanalyst** [comment]
use the option no-status

you can protect the main branch now. I've completed the work I wanted to do
