### ISSUE TITLE
Stop the on-page search from stretching

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#53]
The stretching movement of the search bar on focus causes problems when changing screen size.

Whilst a stretching bar looks nice when looking at the site for a couple of times, it becomes annoying when using the site a lot.

I wonder whether it would be better just to set its size.

**Comment by rawleyfowler** [comment]
@finanalyst I can address this in the changes fixes to the existing bar problems if you'd like. The bar is kind of a mess, I am having to refactor a lot to make small style changes.

**Comment by finanalyst** [comment]
@rawleyfowler please look at this.
There are quite a few problems with the search bar.

I will not open a separate issue, but it is related to this one, is that there is a faint grey line above the search bar. The line is coming from the auto-complete div that is made visible when search produces results. In addition, the div seems to be slightly misplaced upwards. 

I will look at issue #47 which will add info to the items object that the autocomplete handles

**Comment by finanalyst** [comment]
I can't get a screenshot of the problem because it disappears when focus shifts to screenshot app

**Comment by rawleyfowler** [comment]
@finanalyst I am working on a comprehensive patch for most of the searchbar issues reported. When I PR i'll mention the issues that it solves.

**Comment by rawleyfowler** [comment]
@finanalyst I just PR'd for most of the visual problems. I'll look at #47 this weekend.

**Comment by finanalyst** [comment]
closing this as completed
