### ISSUE TITLE
When can we see this on new infrastructure?

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#63]
Currently, I'm building this website and running it at new-raku.finanalyst.org

But I'm using a slightly different installation (eg. I have Collection examples in the more dropdown, which are not included in this repo's templates).

So there are occasional sync errors. It would be good to see how the build works on the new infrastructure

**Comment by dontlaugh** [comment]
The goal is to still package the site as a single container. [This container's `latest` tag **should** be getting updated on every merge to main](https://quay.io/repository/colemanx/raku-doc-website?tab=history).

The is the deployable artifact we're working with. Test locally:

```
[docker|podman] run -p 8080:80 quay.io/colemanx/raku-doc-website
```

As for real infra, with a raku-related DNS record, I am going to try and run this container on the dev instance @rba gave me access to. I'll give it a shot this weekend.

But it will only be _really_ interesting when this same container can be automatically updated. For that, I need to learn a bit more about Portainer's API. Or, alternatively, hand it off to a colleague w/ SSH access for a terminal-based solution (what i'd prefer anyway, tbh).

**Comment by dontlaugh** [comment]
I have put this up on the _dev/playground_ Portainer instance that @rba gave me access to.

Auto-deploy is still being worked out.

http://raku-infra-fsn1-01.rakulang.site:5250/

As is SSL.

**Comment by finanalyst** [comment]
How often is this being refreshed at present? It would be good if a change in the tooling can be seen fairly quickly. I check using new-raku.finanalyst.org, but that is a slightly different build process.

**Comment by dontlaugh** [comment]
Automatic deployment is not implemented yet. It won't refresh until that's done.

**Comment by finanalyst** [comment]
@dontlaugh  I'm trying to create a local docker image so that I can replicate locally what will happen in the production site. Looking at `.build-kite` I see that you 
1. tar the html files, 
2. create a container image with `buildah` using nginx
3. transfer the tar to the container image
4. push the image to a server of yours.

I do not see at which step the tar ball is decompressed. Or does nginx not need for the tarball to be decompressed?

If I just want to serve the files, I can use the cro app in Collection. But the issue of redirects using `.htaccess` has been raised. And also it would be neater for links to be routes rather than html files.

**Comment by dontlaugh** [comment]
This is a nifty little trick of docker/buildah. When you 1) use the `add` command while building a container and, 2) if the file you're adding is an archive, then the archive is automatically uncompressed.

**Comment by finanalyst** [comment]
@dontlaugh  Two things.

a) you create an image with nginx. How can configuration files be added to that image?

b) Rather than have a separate archive script, suppose I write a completion plugin that tar-balls the finished site. Currently, the completion plugin is a Cro app for serving the files. 

The location/name of the tarball could be put into a config file, so a change in the configs would change name / location of the archive.

**Comment by dontlaugh** [comment]
> How can configuration files be added to that image?

If you mean nginx configs, they can be added with an additional `add` command that replaces the file locaed at /etc/nginx/nginx.conf; The nginx configs can be checked into this repo.

> ...suppose I write a completion plugin that tar-balls the finished site.

I'm missing something. Is there something missing from the tarball generated by the current build script?

PS: autodeploy should work now, every hour - here: https://docs-dev.raku.org

Let's make this work with static files + nginx.

**Comment by finanalyst** [comment]
@dontlaugh 
>> ...suppose I write a completion plugin that tar-balls the finished site.

> I'm missing something. Is there something missing from the tarball generated by the current build script?

No, I'm suggesting replacing the explicit archive script with a completion plugin. It would reduce the steps to just `binary_files/build-site`. The --without-completion could be missed as the completion phase would be archiving the static files.

Just seen the new site. Great.

We could close this thread. But could you respond to the completion idea first, or lets have a discussion off-line.

**Comment by dontlaugh** [comment]
Reducing steps here isn't necessarily a good thing, in my opinion. Let's just use what is working for now.
