### ISSUE TITLE
arrow keys in search dropdown don't highlight

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#67]
After searching and getting a dropdown list, the arrow keys are changing the selection (the selected text changes), but there is no highlight indicator on the dropdown itself.

**Comment by coke** [comment]
Also, the text in the search box doesn't reflect the additional info on each line, making this a real usability issue; e.g. "in Class Exception" is only in the dropdown, not the select box, so you have no indication of which of several potentially same-looking rows you've selected.

**Comment by coke** [comment]
The "Enter to select" text is also inaccurate once you start using the arrow keys - enter selects the selected row, not the one that says "Enter to select"

**Comment by finanalyst** [comment]
I had come across these problems myself.
The problem I see here is that the text in the search box is used to filter alternatives, whilst the extra information is not used for filtering.

**Comment by finanalyst** [comment]
These are issues related to the use of the autocomplete jQuery. Problems with this plugin have been raised before, see #30

**Comment by finanalyst** [comment]
This appears to be corrected now. See new-raku.finanalyst.org

**Comment by finanalyst** [comment]
closing this for now as completed
