### ISSUE TITLE
Github merge priviledges removed

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#7]
I cannot push changes from my local repo to the github repo

**Comment by lizmat** [comment]
What is the error?  According to your privileges you should be!

**Comment by lizmat** [comment]
Could you try again?

**Comment by dontlaugh** [comment]
@finanalyst try pushing to a branch besides `main`; does that work?

**Comment by finanalyst** [comment]
I'm trying to work out how to do that.

But pushing to a new branch then merging the branch is a bit frustrating and extra hassle at this very early stage. There are 6 issues I have assigned to myself to work through. 

For at least the next few days, it seems unlikely any one will have read the Collection docs to be able to review my initial work. 

In a sense the changes I'm making now are still a part of the initial commit.

**Comment by finanalyst** [comment]
OK I created a branch second_commit, created a PR, then merged the PR to main.

that is quite a bit of hassle. Can we unblock the main branch for contributors at least for about a week. That's the maximum time I need to get most of the  flaws I see fixed. After a week, I can see its reasonable to protect the main branch again.

**Comment by dontlaugh** [comment]
> Can we unblock the main branch for contributors at least for about a week

I'm afraid we can't. Here are some reasons:

* Others will be contributing code, and pushes to main directly will risk merge conflicts.
* CI pipelines that orchestrate auto-deploy, automated tests, and artifact naming cannot be developed outside of the context of a merge request workflow. Having no such workflow blocks us from developing automation
* It encourages contribution. You know more about this code than anyone, so what we need is for you to help review merge requests, guide new contributors such as myself. We'll find and fix the bugs together :heart:

**Comment by finanalyst** [comment]
@dontlaugh The reasons you cite are exactly the ones I meant when I said that in due course (after about a week from now), I would expect there to be rigidity in rules.
But at the start, before the  initial codebase is complete, this seems to be far more rigidity than is necessary.
commits that are bad can be reverted.
CI has not yet been set up.
So I ask again, purely for the first week, say to Sat Jan 29, allow for commits to main by designated contributors. After Jan 29, protect the main branch as now.

**Comment by dontlaugh** [comment]
Okay, if you insist, we can grant you these special privileges for a week.

Do submit a PR if you think it contains changes that others should be aware of.
