### ISSUE TITLE
Can't search for <==

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#70]
Searching for this seems to automatically convert the search criteria to a unicode arrow symbol, and <== doesn't appear in the dropdown.

**Comment by rawleyfowler** [comment]
I am also confused why unicode conversions happen. For example: << is not converted to unicode but <== is.

**Comment by finanalyst** [comment]
I have some funny problems with the unicode symbols as well.
Sometimes, I notice they are not rendered properly in the drop-down, but I cant find an example as I write.

Some things to consider:
- the data for the search function comes from a json-escaped transformation of the string taken from the pod file.
- the pod file source sometimes uses ASCII equivalents, and sometimes the unicode. So, the problem may not be with the transfer of data into the search function, but with the original data.

To fix these errors, we need to identify where the problems actually exist, and what is the source of the search data. By source, I mean the `=headx` block in the POD6 file. For `<==` above, it would be something like `head1 infix operator <==`.

**Comment by rawleyfowler** [comment]
I'll take a look at solving this.

**Comment by finanalyst** [comment]
Thanks

**Comment by rawleyfowler** [comment]
@finanalyst I am not really able to find a good way to solve this. I think we need to ditch the whole ligature thing in the search bar.

**Comment by finanalyst** [comment]
is solve by #245. this can be closed when #245 lands - waiting for upstream bug to be fixed

**Comment by finanalyst** [comment]
closing as completed
