### ISSUE TITLE
Move "generated from" text

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#88]
E.g.

> Generated from local_raku_docs/doc/Language/intro.pod6 at 2023-02-07T09:47:13Z

Can we move this into a smaller font and into the footer itself? (centered, maybe?)

**Comment by finanalyst** [comment]
Definitely.

As for footer, can we simply have a `License` tab that pops up with the whole 'This website is ...' That would free some space for the generated text.

**Comment by finanalyst** [comment]
completed. Result in footer can be seen in [new-raku](https://new-raku.finanalyst.org)

**Comment by coke** [comment]
Looks good, thanks!
