### ISSUE TITLE
Move from twitter to mastodon

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#91]
> < @lizmat > at the front page, perhaps change Twitter to Mastodon with https://fosstodon.org/@rakulang as link?

**Comment by rawleyfowler** [comment]
I can do this.

**Comment by coke** [comment]
This change doesn't appear on https://new-raku.finanalyst.org/

**Comment by finanalyst** [comment]
This is a sync error. As said before, new-raku is generated from a different repo.
@rawleyfowler changed this in the doc-website document and I did not transfer the change to new-raku.
Fixed now.
