### ISSUE TITLE
generated / license popups bad in dark theme

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#97]
Moving the 'generated' and 'license' info in to popups, using the Bulma css classes works fine in the light theme, but not in the dark theme. (The light theme for these components could be tweaked a bit too ??)

Extra scss styling needs to be added in `Website/plugins/ogdenwebb`. Currently, the styling is coming from `... ogdenwebb/scss/main.scss` which is importing from `... ogdenwebb/bulma/components.scss`. 

Probably the best place to put new dark styling would be `... scss/themes/dark.scss`

**Comment by finanalyst** [comment]
@rawleyfowler could you do this?

**Comment by rawleyfowler** [comment]
@finanalyst Yeah I'll look into it tomorrow.

**Comment by rawleyfowler** [comment]
Should be finished this tomorrow. Sorry. Lots of things popping up!
